# Données

## Importation des packages

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
pd.set_option('display.max_rows', 500)

import requests
from bs4 import BeautifulSoup
import os
import s3fs
import ast
import json

## Lecture des fichiers movies_metadata.csv et credits.csv

Les données de movies_metadata.csv et credits.csv sont des données trouvées sur Kaggle qui centralisent des informations diverses sur des films sortis avant juillet 2017. 

Les variables de movies_metadata.csv sont :
- adult : signification de la variable non connue
- belongs to collection : si le film appartient à une série de film, la variable renseigne les films faisant partie de cette série
- budget : budget du film
- genres : genres du film
- homepage : lien vers le site officiel du film s'il y en a un
- id et imdb_id : identifiants du film
- original_language : langue originale du film
- original_title : titre original du film
- overview : résumé du film
- popularity : popularité du film sur IMDB
- poster_path : lien vers l'affiche du film
- production_countries : pays de production du film
- production_companies : compagnies de production du film
- release_date : date de sortie du film
- revenue : recettes du film
- runtime : durée du film
- spoken_languages : langues parlées dans le film en version originale
- status : si le film est sorti, prévu, annulé, en production etc
- tagline : catchphrase du film
- title : titre anglophone du film
- video : False si le film est sorti au cinéma, True s'il est sorti directement sur Internet et qu'il n'a pas été diffusé au cinéma

Les variables de credits.csv sont :
- cast : casting du film sous forme de liste de dictionnaires
- crew : équipe du film sous forme de liste de dictionnaires

Nous souhaitons à partir de ces données prédire la note de nouveaux films, voir quelles sont les variables les plus décisives pour prédire si un film sera ien reçu par le public et ainsi remarquer (ou non) la prévisibilité du succès d'un film.

Nous pourrons pondérer l'erreur de prévision avec la variable vote_count et faire de la classification non supervisée dans les stats descriptives

In [2]:
os.environ['AWS_S3_ENDPOINT']
S3_ENDPOINT_URL = 'http://' + os.environ['AWS_S3_ENDPOINT']
fs = s3fs.S3FileSystem(client_kwargs = {'endpoint_url' :S3_ENDPOINT_URL })
fs.ls('mlepennec-ensae')
BUCKET = 'mlepennec-ensae'
FILE_KEY_S3 = '/movies_metadata.csv'
FILE_PATH_S3 = BUCKET+FILE_KEY_S3
with fs.open(FILE_PATH_S3, mode = "rb") as file_in : 
    data_movies = pd.read_csv(file_in,sep=',', header=0)

/tmp/ipykernel_53997/2309787388.py:9: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  data_movies = pd.read_csv(file_in,sep=',', header=0)

In [3]:
FILE_KEY_S3 = '/credits.csv'
FILE_PATH_S3 = BUCKET+FILE_KEY_S3
with fs.open(FILE_PATH_S3, mode = "rb") as file_in : 
    data_credits = pd.read_csv(file_in,sep=',', header=0)

## Retraitements

Après première exploration des données movies_metadata, nous avons décidé d'enlever les variables suivantes : adult, homepage, overview, popularity, poster_path, spoken_languages et tagline. En effet, la variable adult présente presque toujours la modalité False et semble avoir peu d'intérêt. La variable homepage renseigne le lien vers le site officiel du film s'il y en a un. La variable overview contient les résumés des films du dataframe, ce qui peut être intéressant à exploiter mais nous avons décidé de ne pas le faire. La variable popularity est la popularité du film sur IMDB au moment où les données ont été extraites, c'est donc une variable qui n'est pas statique et qui est calculée directement par IMDB d'une façon que nous ignorons donc nous ne souhaitons pas la prendre en compte. La variable poster_path indique le lien vers l'affiche du film, nous n'en avons pas besoin. La variable spoken_languages indique les langues parlées durant le film en version originale, nous considérons que cette variable est redondante par rapport à la variable original_language. Enfin la variable tagline indique la catchphrase du film, ce qui est à nos yeux peu utile également.

Nous allons retraiter certaines variables. Par exemple, la variable belongs_to_collection sera transformée en booléen (1 si le film correspond à une série de films, 0 sinon) à laquelle nous ajouterons une variable avec le nombre de films précédents de la série ainsi que la note du film précédent. La variable genres sera décomposée en plusieurs variables genre_1, genre_2 etc. Ce genre de décomposition sera également nécessaire pour les variables production_countries et production_companies

Les variables budget et runtime présentent des valeurs manquantes, que nous allons essayer de compléter avec du web scraping.

Nous allons nous concentrer sur les films qui sont déjà sortis en salle (status = Released et video=False)

Les données du fichier credits.csv vont nous permettre d'ajouter les acteurs principaux et le réalisateur du film à notre jeu de données. Nous souhaitons ajouter des variables relatives à la popularité des acteurs et du réalisateur via du web scraping.

Nous n'allons pas prendre en compte la variable revenue dans l'étude Machine Learning car nous souhaitons être capables de prédire la note d'un film qui ne serait pas encore sorti, donc les recettes du film ne sont pas connues à l'avance.

In [4]:

data_movies_df = data_movies[data_movies['video'] == False]
data_movies_df = data_movies_df[data_movies_df['status'] == 'Released']
data_movies_df = data_movies_df[data_movies_df['vote_count'] > 0]
data_movies_df = data_movies_df.drop(columns=['adult', 'homepage', 'overview', 'popularity', 'poster_path', 'spoken_languages', 'tagline', 'status', 'video'])
data_movies_df = data_movies_df.dropna(subset= ['release_date'])
data_movies_df = data_movies_df.dropna(subset= ['imdb_id'])
data_movies_df = data_movies_df.dropna(subset= ['original_language'])
data_movies_df= data_movies_df.drop_duplicates()
data_movies_df = data_movies_df.groupby('id', group_keys=False).apply(lambda group: group.loc[group['vote_count'] == group['vote_count'].min()]).reset_index(drop=True)

/tmp/ipykernel_53997/913713924.py:9: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  data_movies_df = data_movies_df.groupby('id', group_keys=False).apply(lambda group: group.loc[group['vote_count'] == group['vote_count'].min()]).reset_index(drop=True)

In [5]:
data_movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42028 entries, 0 to 42027
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  4402 non-null   object
 1   budget                 42028 non-null  object
 2   genres                 42028 non-null  object
 3   id                     42028 non-null  object
 4   imdb_id                42028 non-null  object
 5   original_language      42028 non-null  object
 6   original_title         42028 non-null  object
 7   production_companies   42028 non-null  object
 8   production_countries   42028 non-null  object
 9   release_date           42028 non-null  object
 10  revenue                42028 non-null  float64
 11  runtime                41879 non-null  float64
 12  title                  42028 non-null  object
 13  vote_average           42028 non-null  float64
 14  vote_count             42028 non-null  float64
dtypes: float64(4), object(11)
memory usage: 4.8+ MB

### Retraitement des variables budget et runtime

La variable budget a été reconnue comme chaîne de caractères par Python, nous la convertissons donc en numeric. Pour les variables budget et runtime lorsque la valeur n'est pas connue c'est un 0 qui s'affiche, nous remplaçons donc tous les 0 par NaN.

In [6]:
# conversion de "budget" en nombre
#data_movies_df["budget"] = pd.to_numeric(data_movies_df["budget"], errors="coerce")

# budget et duree (runtime) nuls a considerer comme valeurs manquantes
data_movies_df["budget"] = data_movies_df["budget"].replace('0', np.nan)
data_movies_df["runtime"] = data_movies_df["runtime"].replace(0, np.nan)

In [7]:
df=data_movies_df

### Retraitement de la variable belongs_to_collection

Nous souhaitons ajouter un booléen qui vaut 1 si le film fait partie d'une saga de films et 0 sinon, le nom de la saga à laquelle il appartient, le rang du film dans la saga ainsi que le nombre de films que contient la saga au total et la note du film précédent dans la saga.

In [8]:
# belongs to collection : 
# on crée un booleen indic_collec 
df["indic_collec"]  = df["belongs_to_collection"].notna().astype("int8") # int8 → 1 octet par valeur
df["indic_collec"].value_counts()
df_collec = df[df["indic_collec"] == 1]
df_collec['belongs_to_collection'] = df_collec['belongs_to_collection'].apply(ast.literal_eval)

# on cree une fonction pour recuperer le nom de la collection s il est rempli, rien sinon
def recup_collec(x):
    if pd.notna(x):
        try:
            return ast.literal_eval(x)
        except (ValueError, SyntaxError):
            return None
    return x

df['belongs_to_collection'] = df['belongs_to_collection'].apply(recup_collec)
df['nom_collec'] = df['belongs_to_collection'].apply(
            lambda x: x['name'] if isinstance(x, dict) and 'name' in x else None
                                                )

/tmp/ipykernel_53997/4206164378.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_collec['belongs_to_collection'] = df_collec['belongs_to_collection'].apply(ast.literal_eval)

In [9]:
# creation d'une colonne rang
# on trie par collec et date de sortie
df = df.sort_values(by=['nom_collec', 'release_date'], ascending=[True, True])
df["rang"] = np.nan # initialisation
masque = df["nom_collec"].notna() # si collec n'est pas manquant
df.loc[masque, "rang"] = df.loc[masque].groupby("nom_collec").cumcount() + 1
#df.rang.value_counts(dropna=False)

In [10]:
# on rajoute une colonne rang max
df_max_rang = df.groupby('nom_collec')['rang'].max().reset_index()
df_max_rang.rename(columns={'rang': 'max_rang'}, inplace=True)
df = df.merge(df_max_rang, on='nom_collec', how='left')

In [11]:
#  ceux qui n'ont qu'un seul opus present sont a considerer comme ne faisant pas partie d'une serie
condition = (df['rang'] == 1) & (df['max_rang'] == 1)

df.loc[condition, 'indic_collec'] = 0
df.loc[condition, 'nom_collec'] = None
df.loc[condition, 'rang'] = np.nan
df.loc[condition, 'max_rang'] = np.nan

#df['max_rang']

In [12]:
# pour les sagas, on recupere la note de l opus precedent
df_prec = df[df['rang'] >= 1]

df_prec['rang'] += 1  # rang dans df_prec correspondra à rang - 1 dans df
df_prec = df_prec.rename(columns={'vote_average': 'vote_prec'}) # colonne vote_average renommée poru etre gardee lors de la fusion
df_prec = df_prec[['rang','nom_collec','vote_prec']]


# Merge sur nom_collec et rang
df2 = df.merge(df_prec[['nom_collec', 'rang', 'vote_prec']],
                     on=['nom_collec', 'rang'],
                     how='left')

df = df2.drop(columns=['belongs_to_collection'])

/tmp/ipykernel_53997/2582065488.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_prec['rang'] += 1  # rang dans df_prec correspondra à rang - 1 dans df

In [13]:
df.shape

(42028, 19)

### Retraitement de la variable genres

In [14]:
# variable genres : a considerer comme une liste de dictionnaire
df['genres'] = df['genres'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)
# : il peut y en avoir plusieurs : combien maximum?
max_genres = df['genres'].apply(lambda x: len(x) if isinstance(x, list) else 0).max()
#print(f"Nombre maximum de dictionnaires dans 'genres' : {max_genres}")

In [15]:
# Creation des colonnes genre1 à genre8
for i in range(8):
    col_name = f'genre{i+1}'
    df[col_name] = df['genres'].apply(
        lambda x: x[i]['name'] if isinstance(x, list) and len(x) > i and isinstance(x[i], dict) else None
    )

### Retraitement de la variable production_companies

In [16]:
# variable production_companies : a considerer comme une liste de dictionnaire
df['production_companies'] = df['production_companies'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)
# : il peut y en avoir plusieurs : combien maximum?
max_prod = df['production_companies'].apply(lambda x: len(x) if isinstance(x, list) else 0).max()
#print(f"Nombre maximum de dictionnaires dans 'production_companies' : {max_prod}")
# a voir : il ne sera pas pertinent de garder 26 colonnes

In [17]:
# Creation des colonnes prod1 à prod26
for i in range(26):
    col_name = f'prod{i+1}'
    df[col_name] = df['production_companies'].apply(
        lambda x: x[i]['name'] if isinstance(x, list) and len(x) > i and isinstance(x[i], dict) else None
    )

### Retraitement de la variable production_countries

In [18]:
# variable production_countries : a considerer comme une liste de dictionnaire
df['production_countries'] = df['production_countries'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)
# : il peut y en avoir plusieurs : combien maximum?
max_prod = df['production_countries'].apply(lambda x: len(x) if isinstance(x, list) else 0).max()
#print(f"Nombre maximum de dictionnaires dans 'production_countries' : {max_prod}")
# a voir : il ne sera pas pertinent de garder 25 colonnes

In [19]:
# Creation des colonnes pays1 a pays25
for i in range(25):
    col_name = f'pays{i+1}'
    df[col_name] = df['production_countries'].apply(
        lambda x: x[i]['name'] if isinstance(x, list) and len(x) > i and isinstance(x[i], dict) else None
    )

In [20]:
missing_percentage = df.isna().sum()

print('MISSING VALUES :')
if missing_percentage[missing_percentage != 0].empty:
    print('No')
else:
    print(missing_percentage[missing_percentage != 0].sort_values(ascending=False))

MISSING VALUES :
pays22        42027
pays25        42027
pays23        42027
pays24        42027
pays13        42027
pays17        42027
pays16        42027
pays15        42027
pays14        42027
pays18        42027
pays20        42027
pays19        42027
pays21        42027
pays12        42026
genre8        42025
prod26        42025
prod25        42024
pays11        42024
pays10        42023
prod23        42023
prod24        42023
prod22        42020
pays9         42018
prod21        42016
pays8         42012
prod20        42011
prod19        42006
prod18        42003
genre7        42002
pays7         42001
prod17        41996
prod16        41976
prod15        41967
pays6         41963
prod14        41952
prod13        41933
prod12        41899
prod11        41857
genre6        41848
pays5         41817
prod10        41790
prod9         41658
prod8         41483
pays4         41367
prod7         41176
genre5        41036
prod6         40623
pays3         39963
prod5         39690
vote_prec     39300
nom_collec    38013
max_rang      38013
rang          38013
prod4         37776
genre4        37750
pays2         35283
budget        33265
prod3         33183
genre3        28521
prod2         25545
genre2        14820
prod1          9978
pays1          4977
genre1         1653
runtime        1302
dtype: int64

In [21]:
df.shape

(42028, 78)

In [22]:
data_movies_df=df

### Web scraping Wikipédia

Nous souhaitons compléter la variable budget qui présente beaucoup de valeurs manquantes, ainsi qu'ajouter des informations sur les acteurs et réalisateurs.

On ajoute au dataframe les différents url wikipédia possibles pour un film (selon le nom du film, il faut parfois ajouter film ou film + année de sortie à l'url wikipédia pour tomber sur la bonne page wiki)

In [23]:
url_wikipedia_fr = "https://fr.wikipedia.org/wiki/"
url_wikipedia_en = "https://en.wikipedia.org/wiki/"
data_movies_df['url'] = url_wikipedia_en + data_movies_df.title.str.replace(" ", "_")
data_movies_df['url_film'] = url_wikipedia_en + data_movies_df.title.str.replace(" ", "_") + "_(film)"
data_movies_df['release_year'] = data_movies_df.release_date.str[:4]
data_movies_df['url_film_date'] = url_wikipedia_en + data_movies_df.title.str.replace(" ", "_") + "_(film,_" + data_movies_df.release_year + ")"
data_movies_df['id'] = pd.to_numeric(data_movies_df['id'])

On joint les dataframes movies et credits pour ajouter le casting et l'équipe du film.

In [24]:
data_movies_credits = data_movies_df.merge(data_credits.drop_duplicates(), left_on='id', right_on='id', how='left')
data_movies_credits

,budget,genres,id,imdb_id,original_language,original_title,production_companies,production_countries,release_date,revenue,...,pays22,pays23,pays24,pays25,url,url_film,release_year,url_film_date,cast,crew
0,70000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",117263,tt2302755,en,Olympus Has Fallen,"[{'name': 'Nu Image Films', 'id': 925}, {'name...","[{'iso_3166_1': 'US', 'name': 'United States o...",2013-03-20,161025640.0,...,None,None,None,None,https://en.wikipedia.org/wiki/Olympus_Has_Fallen,https://en.wikipedia.org/wiki/Olympus_Has_Fall...,2013,https://en.wikipedia.org/wiki/Olympus_Has_Fall...,"[{'cast_id': 7, 'character': 'Mike Banning', '...","[{'credit_id': '52fe4bafc3a36847f820f62f', 'de..."
1,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",267860,tt3300542,en,London Has Fallen,"[{'name': 'Millennium Films', 'id': 10254}, {'...","[{'iso_3166_1': 'BG', 'name': 'Bulgaria'}, {'i...",2016-03-02,205754447.0,...,None,None,None,None,https://en.wikipedia.org/wiki/London_Has_Fallen,https://en.wikipedia.org/wiki/London_Has_Falle...,2016,https://en.wikipedia.org/wiki/London_Has_Falle...,"[{'cast_id': 3, 'character': 'Mike Banning', '...","[{'credit_id': '5363c191c3a368157d002773', 'de..."
2,NaN,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",1652,tt0109000,de,00 Schneider - Jagd auf Nihil Baxter,"[{'name': 'Senator Film Produktion', 'id': 191}]","[{'iso_3166_1': 'DE', 'name': 'Germany'}]",1994-12-21,0.0,...,None,None,None,None,https://en.wikipedia.org/wiki/00_Schneider_-_J...,https://en.wikipedia.org/wiki/00_Schneider_-_J...,1994,https://en.wikipedia.org/wiki/00_Schneider_-_J...,"[{'cast_id': 2, 'character': '00 Schneider / N...","[{'credit_id': '52fe4309c3a36847f80358a9', 'de..."
3,NaN,"[{'id': 10752, 'name': 'War'}, {'id': 18, 'nam...",19430,tt0046671,de,08/15,[],"[{'iso_3166_1': 'DE', 'name': 'Germany'}]",1954-09-30,0.0,...,None,None,None,None,https://en.wikipedia.org/wiki/08/15,https://en.wikipedia.org/wiki/08/15_(film),1954,"https://en.wikipedia.org/wiki/08/15_(film,_1954)","[{'cast_id': 1, 'character': 'Gefreiter Asch',...","[{'credit_id': '52fe47d89251416c750a758d', 'de..."
4,NaN,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",10035,tt0214388,en,100 Girls,"[{'name': 'Dream Entertainment', 'id': 1630}]","[{'iso_3166_1': 'US', 'name': 'United States o...",2000-09-01,0.0,...,None,None,None,None,https://en.wikipedia.org/wiki/100_Girls,https://en.wikipedia.org/wiki/100_Girls_(film),2000,"https://en.wikipedia.org/wiki/100_Girls_(film,...","[{'cast_id': 16, 'character': 'Matthew', 'cred...","[{'credit_id': '52fe430e9251416c75001dbd', 'de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42028,NaN,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",374471,tt4446472,en,Porto,[],"[{'iso_3166_1': 'PL', 'name': 'Poland'}, {'iso...",2017-09-14,0.0,...,None,None,None,None,https://en.wikipedia.org/wiki/Porto,https://en.wikipedia.org/wiki/Porto_(film),2017,"https://en.wikipedia.org/wiki/Porto_(film,_2017)","[{'cast_id': 7, 'character': 'Mati Vargnier', ...","[{'credit_id': '568024559251412e5200b981', 'de..."
42029,4696772,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",398818,tt5726616,en,Call Me by Your Name,"[{'name': 'Sony Pictures Classics', 'id': 58},...","[{'iso_3166_1': 'BR', 'name': 'Brazil'}, {'iso...",2017-10-27,0.0,...,None,None,None,None,https://en.wikipedia.org/wiki/Call_Me_by_Your_...,https://en.wikipedia.org/wiki/Call_Me_by_Your_...,2017,https://en.wikipedia.org/wiki/Call_Me_by_Your_...,"[{'cast_id': 4, 'character': 'Elio Perlman', '...","[{'credit_id': '5742ea0ec3a3686c8c001a6e', 'de..."
42030,NaN,"[{'id': 99, 'name': 'Documentary'}]",359749,tt4372240,en,78/52,"[{'name': 'Exhibit A Pictures', 'id': 63267}]","[{'iso_3166_1': 'US', 'name': 'United States o...",2017-11-03,0.0,...,None,None,None,None,https://en.wikipedia.org/wiki/78/52,https://en.wikipedia.org/wiki/78/52_(film),2017,"https://en.wikipedia.org/wiki/78/52_(film,_2017)","[{'cast_id': 9, 'character': 'Himself', 'credi...","[{'credit_id': '586180ddc3a3681a7d030ed5', 'de..."
42031,NaN,[],413992,tt2582498,en,Sweet Virginia,[],[],2017-11-17,0.0,...,None,None,None,None,https://en.wikipedia.org/wiki/Sweet_Virginia,https://en.wikipedia.org/wiki/Sweet_Virginia_(...,2017,https://en.wikipedia.org/wiki/Sweet_Virginia_(...,"[{'cast_id': 4, 'character': 'Sam', 'credit_id...","[{'credit_id': '57cb45dfc3a3685a530061d7', 'de..."
42032,NaN,"[{'id': 35, 'name': 'Comedy'}, {'id': 10402, '...",341689,tt3859310,en,How to Talk to Girls at Parties,"[{'name': 'HanWay Films', 'id': 2395}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",2017-12-27,0.0,...,None,None,None,None,https://en.wikipedia.org/wiki/How_to_Talk_to_G...,https://en.wikipedia.org/wiki/How_to_Talk_to_G...,2017,https://en.wikipedia.org/wiki/How_to_Talk_to_G...,"[{'cast_id': 4, 'character': 'Zan', 'credit_id...","[{'credit_id': '57f11a4e9251416d9c003884', 'de..."

In [25]:
data_movies_credits.shape

(42033, 84)

On retraite les colonnes cast et crew pour que Python les reconnaissent en tant que liste de dictionnaires.

In [26]:
data_movies_credits = data_movies_credits.dropna(subset= ['cast'])

data_movies_credits['cast'] = data_movies_credits['cast'].apply(ast.literal_eval)
data_movies_credits['crew'] = data_movies_credits['crew'].apply(ast.literal_eval)

In [27]:
data_movies_credits["nb_acteurs"] = data_movies_credits["cast"].apply(len)
films_par_nombre_acteurs = data_movies_credits["nb_acteurs"].value_counts().sort_index()
films_par_nombre_acteurs

nb_acteurs
0      1718
1      1113
2       764
3       969
4      2214
5      2440
6      2461
7      2554
8      2569
9      2437
10     2623
11     2175
12     1973
13     1732
14     1527
15     2370
16     1324
17     1065
18      794
19      766
20      722
21      572
22      468
23      401
24      342
25      300
26      269
27      243
28      230
29      190
30      175
31      213
32      151
33      127
34      135
35      117
36      105
37       89
38       94
39       68
40       75
41       82
42       70
43       59
44       51
45       54
46       59
47       61
48       44
49       49
50       40
51       57
52       40
53       35
54       34
55       38
56       37
57       25
58       33
59       21
60       22
61       19
62       22
63       15
64       12
65       25
66       16
67       15
68       14
69       13
70       11
71       13
72       11
73       15
74       11
75       12
76       13
77        7
78        7
79        8
80       13
81        7
82        7
83        5
84        8
85        7
86        3
87        8
88        2
89        4
90        3
91        2
92        4
93        1
94        1
95        5
96        4
97        2
98        5
99        3
100       4
101       6
102       1
103       2
104       3
105       5
106       4
107       1
108       3
109       1
110       4
111       1
112       2
113       2
114       4
115       3
117       3
118       3
120       1
121       2
122       2
123       1
124       1
125       2
128       3
130       1
131       1
133       1
134       1
136       1
137       2
140       1
141       2
143       1
145       1
151       1
152       2
156       1
158       1
159       2
165       1
167       1
168       1
171       1
172       1
183       1
185       1
208       2
213       1
224       1
313       1
Name: count, dtype: int64

In [28]:
for i in range(36):
    col_name = f'acteur{i+1}'
    data_movies_credits[col_name] = data_movies_credits['cast'].apply(
        lambda x: x[i]['name'] if isinstance(x, list) and len(x) > i and isinstance(x[i], dict) else None
    )

On ajoute les colonnes correspondant aux 4 acteurs principaux du film et une colonne pour le réalisateur du film.

In [29]:

data_movies_credits['realisateur'] = data_movies_credits['crew'].apply(
    lambda lst: lst['job' == 'Director']['name'] if isinstance(lst, list) and len(lst) > 0 else None
)


data_movies_credits = data_movies_credits.drop(columns=['cast', 'crew', 'genres', 'production_companies', 'production_countries'])

In [30]:
data_movies_credits = data_movies_credits.drop_duplicates()
indices_a_exclure = [17411, 23836, 35546, 39616]
data_movies_credits = data_movies_credits.drop(indices_a_exclure)

In [31]:
data_movies_credits.shape

(42028, 117)

In [ ]:
data_movies_credits[data_movies_credits["budget"].isna()].shape

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36'
}

Fonction pour trouver le budget d'un film avec l'url wikipédia

In [ ]:
def extraire_budget_depuis_wikipedia(url):
    try:
        # Charger la page
        response = requests.get(url, headers=headers)
        response.raise_for_status()

        # Parser le HTML
        soup = BeautifulSoup(response.content, 'html.parser')

        # Trouver l'infobox (il peut y avoir plusieurs classes, mais 'infobox' est souvent commun)
        infobox = soup.find('table', class_='infobox')

        if infobox is None:
            return None  # Pas d'infobox trouvée

        # Chercher les lignes de l'infobox
        rows = infobox.find_all('tr')

        for row in rows:
            header = row.find('th')
            if header and 'budget' in header.get_text(strip=True).lower():
                # Trouver la cellule contenant la valeur
                value_cell = row.find('td')
                if value_cell:
                    return value_cell.get_text(separator=" ", strip=True)

        return None  # Pas de ligne contenant "budget"

    except Exception as e:
        print(f"Erreur lors du traitement de {url}: {e}")
        return None

In [ ]:
data['budget_url'] = data['url'].apply(extraire_budget_depuis_wikipedia)
data['budget_url_film'] = data['url_film'].apply(extraire_budget_depuis_wikipedia)
data['budget_url_film_date'] = data['url_film_date'].apply(extraire_budget_depuis_wikipedia)

# Ton DataFrame à sauvegarder
# Exemple : df = pd.DataFrame({'col1': [1, 2], 'col2': ['a', 'b']})
BUCKET = 'mlepennec-ensae'

FILE_OUT_S3 = '/movies_budget.csv'  # Chemin dans le bucket
FILE_OUT_PATH = BUCKET + FILE_OUT_S3       # Chemin complet S3

# Écriture vers S3
with fs.open(FILE_OUT_PATH, mode='w') as f_out:
    data.to_csv(f_out, index=False)

In [32]:
FILE_KEY_S3 = '/movies_budget.csv'
FILE_PATH_S3 = BUCKET+FILE_KEY_S3
with fs.open(FILE_PATH_S3, mode = "rb") as file_in : 
    data_budget = pd.read_csv(file_in,sep=',', header=0)

/tmp/ipykernel_53997/1137755944.py:4: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  data_budget = pd.read_csv(file_in,sep=',', header=0)

In [33]:
df=data_movies_credits.merge(data_budget[["id", "budget_url", "budget_url_film", "budget_url_film_date"]].drop_duplicates(),how='left', left_on='id', right_on='id')

In [34]:
df.shape

(42028, 120)

### Retraitement de la variable budget

In [ ]:

# Création de la colonne 'budget_final'
df['budget_final'] = (
    df['budget']
    .fillna(df["budget_url"])
    .fillna(df['budget_url_film'])
    .fillna(df['budget_url_film_date'])
)

In [ ]:
FILE_OUT_S3 = '/movies_credits_budget.csv'  # Chemin dans le bucket
FILE_OUT_PATH = BUCKET + FILE_OUT_S3       # Chemin complet S3

# Écriture vers S3
with fs.open(FILE_OUT_PATH, mode='w') as f_out:
    df.to_csv(f_out, index=False)

In [ ]:
df[df["budget_final"].isna()].shape

In [ ]:
import re
import pandas as pd

def nettoyer_budget(budget):
    if pd.isna(budget):
        return budget  # Laisse les NaN inchangés
    # Convertit en chaîne
    budget_str = str(budget)
    # Supprime la partie entre crochets (avec crochets et espaces autour)
    budget_sans_crochets = re.sub(r'\s*\[\s*.*?\s*\]', '', budget_str)
    # Supprime les virgules
    budget_sans_virgules = budget_sans_crochets.replace(',', '')
    # Supprime les espaces résiduels
    return budget_sans_virgules.strip()

df['budget_nettoye'] = df['budget_final'].apply(nettoyer_budget)

In [ ]:
df['budget_nettoye'].value_counts().head(50)

In [ ]:
def convertir_budget(chaine):
    if not isinstance(chaine, str):
        return None
    
    chaine = chaine.strip()

    # Cas 1 : $x million (avec x décimal ou entier)
    match_million = re.match(r'^\$([\d\.]+)\s+million$', chaine, re.IGNORECASE)
    if match_million:
        x = float(match_million.group(1))
        return str(int(x * 1_000_000))

    # Cas 2 : $x (valeur directe, sans "million")
    match_direct = re.match(r'^\$([\d,\.]+)$', chaine)
    if match_direct:
        x_str = match_direct.group(1).replace(',', '')  # supprime les virgules si présentes
        try:
            x = float(x_str)
            return str(int(x)) if x.is_integer() else str(x)
        except ValueError:
            return None

    # Sinon : format non reconnu
    return None

df['budget_converti'] = df['budget_nettoye'].apply(convertir_budget)
df['budget_converti'] = df['budget_converti'].fillna(df["budget_nettoye"])

In [ ]:
df['budget_converti'][24000]

In [ ]:

def convertir_crore(chaine):
    if not isinstance(chaine, str):
        return None
    
    chaine = chaine.strip()

    # ₹x crore
    match_crore = re.match(r'^₹\s*([\d\.]+)\s*crore$', chaine, re.IGNORECASE)
    if match_crore:
        x = float(match_crore.group(1))
        return str(x * 113000)

    # ₹x million
    match_million = re.match(r'^₹\s*([\d\.]+)\s*million$', chaine, re.IGNORECASE)
    if match_million:
        x = float(match_million.group(1))
        return str(x * 0.011)

    # Aucun format reconnu
    return None

df['budget_converti2'] = df['budget_converti'].apply(convertir_crore)
df['budget_converti2'] = df['budget_converti2'].fillna(df["budget_converti"])

In [ ]:
import pandas as pd

def est_chaine_numerique(val):
    if not isinstance(val, str):
        return False
    try:
        float(val)
        return True
    except ValueError:
        return False

# Filtrer les lignes où 'budget' N'est PAS une chaîne numérique
df_avec_budget=df[~df['budget_final'].isna()]
df_filtré = df_avec_budget[~df_avec_budget['budget_converti2'].apply(est_chaine_numerique)]
df_filtré

In [ ]:
df['release_year'].value_counts()

In [ ]:
df_nan_budget = df[df['release_year']<1960]

# Compter le nombre de lignes par 'release_year'
count_by_year = df_nan_budget.groupby('budget_final').size()
count_by_year

In [ ]:
df[df['budget_final'].isna() & (df['release_year'] < 1960)]

### Web scraping acteurs

In [35]:
colonnes_acteurs = [col for col in df.columns if col.startswith('acteur')]
tous_les_acteurs = df[colonnes_acteurs].values.flatten()
acteurs_uniques = pd.Series(tous_les_acteurs).dropna().unique().tolist()
acteurs_uniques = pd.DataFrame(acteurs_uniques, columns=['acteur'])

acteurs_uniques

                  acteur
0          Gerard Butler
1          Aaron Eckhart
2         Angela Bassett
3         Morgan Freeman
4         Radha Mitchell
...                  ...
180640    Hebe Beardsall
180641        Lara Peake
180642  David McCarrison
180643     Alice Sanders
180644      Mikko Makela

[180645 rows x 1 columns]

In [37]:
acteurs_uniques['url_acteur']= url_wikipedia_en + acteurs_uniques.acteur.str.replace(" ", "_")
acteurs_uniques

                  acteur                                      url_acteur
0          Gerard Butler     https://en.wikipedia.org/wiki/Gerard_Butler
1          Aaron Eckhart     https://en.wikipedia.org/wiki/Aaron_Eckhart
2         Angela Bassett    https://en.wikipedia.org/wiki/Angela_Bassett
3         Morgan Freeman    https://en.wikipedia.org/wiki/Morgan_Freeman
4         Radha Mitchell    https://en.wikipedia.org/wiki/Radha_Mitchell
...                  ...                                             ...
180640    Hebe Beardsall    https://en.wikipedia.org/wiki/Hebe_Beardsall
180641        Lara Peake        https://en.wikipedia.org/wiki/Lara_Peake
180642  David McCarrison  https://en.wikipedia.org/wiki/David_McCarrison
180643     Alice Sanders     https://en.wikipedia.org/wiki/Alice_Sanders
180644      Mikko Makela      https://en.wikipedia.org/wiki/Mikko_Makela

[180645 rows x 2 columns]

In [38]:
FILE_OUT_S3 = '/acteurs_df.csv'  # Chemin dans le bucket
FILE_OUT_PATH = BUCKET + FILE_OUT_S3       # Chemin complet S3

# Écriture vers S3
with fs.open(FILE_OUT_PATH, mode='w') as f_out:
    acteurs_uniques.to_csv(f_out, index=False)

In [69]:
AWARD_KEYWORDS = [
    r'Academy Awards', r'Oscar', 'Oscars', r'Golden Globe Awards', 'Golden Globe', r'BAFTA', r'BAFTA Awards', 'BAFTAs',
    r'Filmfare', r'National Film Award', r'Dadasaheb Phalke', r'César', 'Césars',
    r'Palme d\'Or', r'Palmes d\'Or',  r'Golden Lion', r'Lion d\'Or', r'Ours d\'Or', r'Tony',
    r'Emmy Awards', r'Grammy Awards', r'Screen Actors Guild Awards', r'IIFA', r'Goya', r'David di Donatello'
]

In [75]:
import requests
from bs4 import BeautifulSoup

def get_actor_awards_structured(url):
    """
    Récupère les récompenses et nominations d'un acteur depuis sa page Wikipédia anglaise,
    et les retourne sous forme structurée.
    
    Args:
        url (str): URL de la page Wikipédia de l'acteur (en anglais)
    
    Returns:
        list: Liste de dictionnaires contenant les récompenses et nominations
    """
    headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36'
}
    print(url)
    try:
        response = requests.get(url, headers=headers)

    except Exception:
        return [404]
    try:
        soup = BeautifulSoup(response.text, 'html.parser')
    
    # Chercher toutes les sections qui concernent Awards / Nominations
        awards_sections = []
        for header in soup.find_all(['h2','h3']):
            if 'award' in header.get_text().strip().lower() or 'accolade' in header.get_text().strip().lower():
                awards_sections.append(header)
    
        if not awards_sections:
            return []

        awards_list = []

        for section in awards_sections:
            sibling=section.find_previous().find_next_sibling()
    
            pattern="list of awards and nominations received by"
            if pattern in section.find_previous().find_next_sibling().get_text().lower():

                new_url= "https://en.wikipedia.org/wiki/" +'List_of_awards_and_nominations_received_by_'+url[len(url_wikipedia_en):]

                response = requests.get(new_url, headers=headers)
                soup = BeautifulSoup(response.text, 'html.parser')
        
                awards_sections = []
                for header in soup.find_all(['h2','h3']):
                    if header.get_text() in AWARD_KEYWORDS:
                        awards_sections.append(header)
        
                awards_list=["Page des awards"]
                for section in awards_sections:
                    sibling=section.find_previous().find_next_sibling()
                    if sibling.name == 'table' and 'wikitable' in sibling.get('class', []):
                        for row in sibling.find_all('tr')[1:]:  # ignorer l'entête
                            cols = [c.get_text(separator=" ", strip=True) for c in row.find_all(['td', 'th'])]
                            if len(cols) >= 3:
                                awards_list.append({
                                "year": cols[0],
                                "award": cols[1],
                                "result": cols[2],
                                "project": cols[3] if len(cols) > 3 else None
                            })
                return awards_list
            else:
                if sibling.name == 'table' and 'wikitable' in sibling.get('class', []):
                    for row in sibling.find_all('tr')[1:]:  # ignorer l'entête
                        cols = [c.get_text(separator=" ", strip=True) for c in row.find_all(['td', 'th'])]
                        if len(cols) >= 3:
                            awards_list.append({
                                "year": cols[0],
                                "award": cols[1],
                                "result": cols[2],
                                "project": cols[3] if len(cols) > 3 else None
                            })


                elif sibling.name == 'ul':
                        for li in sibling.find_all('li'):
                            text = li.get_text(separator=" ", strip=True)
                    # On peut essayer d'extraire l'année si elle est en début de texte
                            parts = text.split("–")  # souvent "2020 – Award Name"
                            if len(parts) == 2:
                                year, award_name = parts
                            else:
                                year, award_name = None, text
                            awards_list.append({
                            "year": year.strip() if year else None,
                            "award": award_name.strip(),
                            "result": None,  # pas toujours disponible ici
                            "project": None  # pas toujours disponible ici
                        })

        return awards_list
    except Exception:
        return ["Erreur"]

In [4]:
os.environ['AWS_S3_ENDPOINT']
S3_ENDPOINT_URL = 'http://' + os.environ['AWS_S3_ENDPOINT']
fs = s3fs.S3FileSystem(client_kwargs = {'endpoint_url' :S3_ENDPOINT_URL })
fs.ls('mlepennec-ensae')
BUCKET = 'mlepennec-ensae'
FILE_OUT_S3 = '/acteurs_df.csv'  # Chemin dans le bucket
FILE_OUT_PATH = BUCKET + FILE_OUT_S3       # Chemin complet S3

# Écriture vers S3
with fs.open(FILE_OUT_PATH, mode='rb') as f_out:
    acteurs_df=pd.read_csv(f_out)

In [37]:
acteurs_df_4 = acteurs_df.iloc[135001:len(acteurs_df)]
acteurs_df_4

,acteur,url_acteur
135001,Michele Thevenet,https://en.wikipedia.org/wiki/Michele_Thevenet
135002,Anna-Katharina Schwabroh,https://en.wikipedia.org/wiki/Anna-Katharina_S...
135003,Michael Finger,https://en.wikipedia.org/wiki/Michael_Finger
135004,Noa Strupler,https://en.wikipedia.org/wiki/Noa_Strupler
135005,Maria Boettner,https://en.wikipedia.org/wiki/Maria_Boettner
...,...,...
180640,Hebe Beardsall,https://en.wikipedia.org/wiki/Hebe_Beardsall
180641,Lara Peake,https://en.wikipedia.org/wiki/Lara_Peake
180642,David McCarrison,https://en.wikipedia.org/wiki/David_McCarrison
180643,Alice Sanders,https://en.wikipedia.org/wiki/Alice_Sanders
180644,Mikko Makela,https://en.wikipedia.org/wiki/Mikko_Makela

In [38]:
url_wikipedia_en = "https://en.wikipedia.org/wiki/"
acteurs_df_4['awards_info'] = acteurs_df_4['url_acteur'].apply(get_actor_awards_structured)
FILE_OUT_S3 = '/acteurs_df_4.csv'  # Chemin dans le bucket
FILE_OUT_PATH = BUCKET + FILE_OUT_S3       # Chemin complet S3

# Écriture vers S3
with fs.open(FILE_OUT_PATH, mode='w') as f_out:
    acteurs_df_4.to_csv(f_out, index=False)

https://en.wikipedia.org/wiki/Michele_Thevenet
https://en.wikipedia.org/wiki/Anna-Katharina_Schwabroh
https://en.wikipedia.org/wiki/Michael_Finger
https://en.wikipedia.org/wiki/Noa_Strupler
https://en.wikipedia.org/wiki/Maria_Boettner
https://en.wikipedia.org/wiki/Gilles_Tschudi
https://en.wikipedia.org/wiki/Roger_McGuinn
https://en.wikipedia.org/wiki/Rachael_Murphy
https://en.wikipedia.org/wiki/Elena_Satine
https://en.wikipedia.org/wiki/Alma_Saraci
https://en.wikipedia.org/wiki/Brian_Henderson
https://en.wikipedia.org/wiki/Kyle_Archer
https://en.wikipedia.org/wiki/Laura_Lance
https://en.wikipedia.org/wiki/Gil_Darnell
https://en.wikipedia.org/wiki/Ajla_Hodzic
https://en.wikipedia.org/wiki/Soo-Ae
https://en.wikipedia.org/wiki/Choi_Jae-woong
https://en.wikipedia.org/wiki/Martha_West
https://en.wikipedia.org/wiki/Anabolena_Rodriguez
https://en.wikipedia.org/wiki/Zak_Davies
https://en.wikipedia.org/wiki/Freya_Parks
https://en.wikipedia.org/wiki/Christopher_Dunkin
https://en.wikipedia.org/wiki/Gene_Goodman
https://en.wikipedia.org/wiki/Harrison_Sansostri
https://en.wikipedia.org/wiki/Dagmara_Krasowska
https://en.wikipedia.org/wiki/Dominika_Gwit
https://en.wikipedia.org/wiki/Magdalena_Ciurzynska
https://en.wikipedia.org/wiki/Izabela_Kuna
https://en.wikipedia.org/wiki/Ewa_Kolasińska
https://en.wikipedia.org/wiki/Zuzanna_Madejska
https://en.wikipedia.org/wiki/Tomasz_Zaród
https://en.wikipedia.org/wiki/Uula_Laakso
https://en.wikipedia.org/wiki/Ursula_Salo
https://en.wikipedia.org/wiki/Kerry_Beyer
https://en.wikipedia.org/wiki/Julin_Jean
https://en.wikipedia.org/wiki/Amy_Morris
https://en.wikipedia.org/wiki/Roxy_Vandiver
https://en.wikipedia.org/wiki/Jon_Paul_Burkhart
https://en.wikipedia.org/wiki/Megan_Moser
https://en.wikipedia.org/wiki/John_Lansch
https://en.wikipedia.org/wiki/Alyssia_Dujmovich
https://en.wikipedia.org/wiki/Matt_Tramel
https://en.wikipedia.org/wiki/Denise_Williamson
https://en.wikipedia.org/wiki/Áurea_Baptista
https://en.wikipedia.org/wiki/Ismael_Caneppele
https://en.wikipedia.org/wiki/Tuane_Eggers
https://en.wikipedia.org/wiki/Henrique_Larré
https://en.wikipedia.org/wiki/Samuel_Reginatto
https://en.wikipedia.org/wiki/Ryô_Iwamatsu
https://en.wikipedia.org/wiki/Junko_Fuji
https://en.wikipedia.org/wiki/Miu_Naraki
https://en.wikipedia.org/wiki/Hugo_Arbues
https://en.wikipedia.org/wiki/Miriam_Correa
https://en.wikipedia.org/wiki/Tomás_del_Estal
https://en.wikipedia.org/wiki/Javier_Mejía
https://en.wikipedia.org/wiki/Kaiet_Rodríguez
https://en.wikipedia.org/wiki/Raquel_Salvador
https://en.wikipedia.org/wiki/Elizabeth_Jackson
https://en.wikipedia.org/wiki/Tammi_Arender
https://en.wikipedia.org/wiki/Jake_Austin_Walker
https://en.wikipedia.org/wiki/Giacomo_Talamini
https://en.wikipedia.org/wiki/Phillip_Sacramento
https://en.wikipedia.org/wiki/Patrizia_Liccardi
https://en.wikipedia.org/wiki/Laura_Post
https://en.wikipedia.org/wiki/Nicola_Cecconi
https://en.wikipedia.org/wiki/Glenn_X._Govan
https://en.wikipedia.org/wiki/Andrea_Furlan
https://en.wikipedia.org/wiki/William_Martin
https://en.wikipedia.org/wiki/Giovanni_Contessotto
https://en.wikipedia.org/wiki/Marco_Saran
https://en.wikipedia.org/wiki/Lee_Joon
https://en.wikipedia.org/wiki/Ill-Young_Kim
https://en.wikipedia.org/wiki/Kylie_Goldstein
https://en.wikipedia.org/wiki/Sungwoong_Yoon
https://en.wikipedia.org/wiki/Eleonore_Weisgerber
https://en.wikipedia.org/wiki/Wladimir_Tarasjanz
https://en.wikipedia.org/wiki/Kai_Fung_Rieck
https://en.wikipedia.org/wiki/Anna_Sawai
https://en.wikipedia.org/wiki/Thorston_Manderlay
https://en.wikipedia.org/wiki/Richard_van_Weyden
https://en.wikipedia.org/wiki/Mina_Ghousi
https://en.wikipedia.org/wiki/Hans_Hohlbein
https://en.wikipedia.org/wiki/Nhi_Ngoc_Nguyen-Hermann
https://en.wikipedia.org/wiki/Jens_Neuhaus
https://en.wikipedia.org/wiki/Patriq_Pinheiro
https://en.wikipedia.org/wiki/Matthias_Schendel
https://en.wikipedia.org/wiki/Johannes_Ahn
https://en.wikipedia.org/wiki/Hoang_Dang-Vu
https://en.wikipedia.org/wiki/Frankie_Shaw
https://en.wikipedia.org/wiki/John_Farrage
https://en.wikipedia.org/wiki/Nina_Ivanišin
https://en.wikipedia.org/wiki/Peter_Musevski
https://en.wikipedia.org/wiki/Maruša_Kink
https://en.wikipedia.org/wiki/Uroš_Furst
https://en.wikipedia.org/wiki/Dejan_Spasic
https://en.wikipedia.org/wiki/Aljoša_Kovačić
https://en.wikipedia.org/wiki/Andrej_Murenc
https://en.wikipedia.org/wiki/Aleš_Valič
https://en.wikipedia.org/wiki/Sophie_Cattani
https://en.wikipedia.org/wiki/Maxime_Renard
https://en.wikipedia.org/wiki/Ludo_Harley
https://en.wikipedia.org/wiki/Gabin_Lefebvre
https://en.wikipedia.org/wiki/Quentin_Gonzalez
https://en.wikipedia.org/wiki/Ellis_Cashmore
https://en.wikipedia.org/wiki/Max_Clifford
https://en.wikipedia.org/wiki/Richard_Curtis
https://en.wikipedia.org/wiki/Josef_d'Bache-Kane
https://en.wikipedia.org/wiki/Nick_Davies
https://en.wikipedia.org/wiki/Charlotte_de_Barker
https://en.wikipedia.org/wiki/Emma_Freud
https://en.wikipedia.org/wiki/Robert_Galinsky
https://en.wikipedia.org/wiki/Jake_Halpern
https://en.wikipedia.org/wiki/Midge_Ure
https://en.wikipedia.org/wiki/Yousef_Amin
https://en.wikipedia.org/wiki/Andrew_Rybak
https://en.wikipedia.org/wiki/Caroline_Couret-Delegue
https://en.wikipedia.org/wiki/Chi_Cao
https://en.wikipedia.org/wiki/Chengwu_Guo
https://en.wikipedia.org/wiki/Wen_Bin_Huang
https://en.wikipedia.org/wiki/Camilla_Vergotis
https://en.wikipedia.org/wiki/Madeleine_Eastoe
https://en.wikipedia.org/wiki/Steven_Heathcote
https://en.wikipedia.org/wiki/Yun-ah_Song
https://en.wikipedia.org/wiki/Yang_Eun-yong
https://en.wikipedia.org/wiki/Tara_Alice_Scully
https://en.wikipedia.org/wiki/Niamh_Shaw
https://en.wikipedia.org/wiki/Henri-Georges_Clouzot
https://en.wikipedia.org/wiki/Dinos_Avgoustidis
https://en.wikipedia.org/wiki/Yorgos_Chraniotis
https://en.wikipedia.org/wiki/Apostolis_Totsikas
https://en.wikipedia.org/wiki/Anthony_Burk
https://en.wikipedia.org/wiki/Polina_Pluchek
https://en.wikipedia.org/wiki/Yana_Troyanova
https://en.wikipedia.org/wiki/Andrei_Dymshakov
https://en.wikipedia.org/wiki/Veronika_Lysakova
https://en.wikipedia.org/wiki/Miguel_Angel_Perez
https://en.wikipedia.org/wiki/Eva_Molina
https://en.wikipedia.org/wiki/Roger_Sharpe
https://en.wikipedia.org/wiki/Rick_Stetta
https://en.wikipedia.org/wiki/Pat_Lawlor
https://en.wikipedia.org/wiki/Steve_Epstein
https://en.wikipedia.org/wiki/Sam_Harvey
https://en.wikipedia.org/wiki/Tim_Arnold
https://en.wikipedia.org/wiki/Lyman_Sheats
https://en.wikipedia.org/wiki/John_Broughton
https://en.wikipedia.org/wiki/Josh_Pingeek_Kaplan
https://en.wikipedia.org/wiki/Gary_Stern
https://en.wikipedia.org/wiki/Donovan_Stepp
https://en.wikipedia.org/wiki/Koi_Morris
https://en.wikipedia.org/wiki/Neil_Shatz
https://en.wikipedia.org/wiki/Sina_Tkotsch
https://en.wikipedia.org/wiki/Michael_Keseroglu
https://en.wikipedia.org/wiki/Aaron_Le
https://en.wikipedia.org/wiki/Frank_Roder
https://en.wikipedia.org/wiki/Alena_Pfanz
https://en.wikipedia.org/wiki/Richard_Riddell
https://en.wikipedia.org/wiki/Richard_Shanks
https://en.wikipedia.org/wiki/Bruce_Crawford
https://en.wikipedia.org/wiki/Cassandra_Sawtell
https://en.wikipedia.org/wiki/Craig_Fraser
https://en.wikipedia.org/wiki/Sari_Lennick
https://en.wikipedia.org/wiki/Aaron_Wolff
https://en.wikipedia.org/wiki/Jessica_McManus
https://en.wikipedia.org/wiki/Brent_Braunschweig
https://en.wikipedia.org/wiki/David_Kang
https://en.wikipedia.org/wiki/Benjamin_Portnoe
https://en.wikipedia.org/wiki/Jon_Kaminski_Jr.
https://en.wikipedia.org/wiki/Ari_Hoptman
https://en.wikipedia.org/wiki/Kainaz_Motivala
https://en.wikipedia.org/wiki/Namit_Das
https://en.wikipedia.org/wiki/Shikha_Talsania
https://en.wikipedia.org/wiki/Benjamin_Helstad
https://en.wikipedia.org/wiki/Emir_Mulasmanovic
https://en.wikipedia.org/wiki/Chase_Ryan_Jeffery
https://en.wikipedia.org/wiki/Elan_Moss-Bachrach
https://en.wikipedia.org/wiki/Bo_Burnham
https://en.wikipedia.org/wiki/Ben_Marten
https://en.wikipedia.org/wiki/Bridgette_Pechman
https://en.wikipedia.org/wiki/Michael_Dailey
https://en.wikipedia.org/wiki/Jean_Lyle_Lepard
https://en.wikipedia.org/wiki/Samantha_Moltmaker
https://en.wikipedia.org/wiki/Matt_Lockwood
https://en.wikipedia.org/wiki/Ruth_Crawford
https://en.wikipedia.org/wiki/Jacquelyn_Evola
https://en.wikipedia.org/wiki/David_Fletcher
https://en.wikipedia.org/wiki/Andrea_Langmeyer
https://en.wikipedia.org/wiki/Barbara_Dacko
https://en.wikipedia.org/wiki/Brian_Matthew_Richardson
https://en.wikipedia.org/wiki/Tom_Whalen
https://en.wikipedia.org/wiki/Alisha_Gellin
https://en.wikipedia.org/wiki/Duncan_Hursley
https://en.wikipedia.org/wiki/Alexander_Zikakis
https://en.wikipedia.org/wiki/Kyra_D._Jackson
https://en.wikipedia.org/wiki/Bettina_Beckman
https://en.wikipedia.org/wiki/Brandan_Gugula
https://en.wikipedia.org/wiki/Andrea_Harrison
https://en.wikipedia.org/wiki/Connell_Brown
https://en.wikipedia.org/wiki/Renee_Scavone
https://en.wikipedia.org/wiki/Stephanie_Scarletta
https://en.wikipedia.org/wiki/Karan_Batta
https://en.wikipedia.org/wiki/Gary_Wojnar
https://en.wikipedia.org/wiki/Jodi_Gabrielle_Beals
https://en.wikipedia.org/wiki/Ryan_Buck
https://en.wikipedia.org/wiki/Matthew_Cieslinski
https://en.wikipedia.org/wiki/Evan_Scott_Perry
https://en.wikipedia.org/wiki/Hiroaki_Murakami
https://en.wikipedia.org/wiki/Kōsuke_Toriumi
https://en.wikipedia.org/wiki/Rika_Morinaga
https://en.wikipedia.org/wiki/Arisa_Ogasawara
https://en.wikipedia.org/wiki/Takashi_Taniguchi
https://en.wikipedia.org/wiki/Devin_McGinn
https://en.wikipedia.org/wiki/Gregg_Lawrence
https://en.wikipedia.org/wiki/Edmund_Lupinski
https://en.wikipedia.org/wiki/Leah_McKendrick
https://en.wikipedia.org/wiki/Ethan_Wilde
https://en.wikipedia.org/wiki/Jessica_Kinney
https://en.wikipedia.org/wiki/Harry_Karp
https://en.wikipedia.org/wiki/Douglas_Jantzen_Jr.
https://en.wikipedia.org/wiki/Barak_Hardley
https://en.wikipedia.org/wiki/Justin_Giddings
https://en.wikipedia.org/wiki/Bryce_Hurless
https://en.wikipedia.org/wiki/Max_Huber
https://en.wikipedia.org/wiki/Rene_Mousseux
https://en.wikipedia.org/wiki/Aynn_Kirby
https://en.wikipedia.org/wiki/Nikki_Kelly
https://en.wikipedia.org/wiki/Jonathan_Lund
https://en.wikipedia.org/wiki/Abigail_Chu
https://en.wikipedia.org/wiki/Stephanie_Baird
https://en.wikipedia.org/wiki/Amanda_Brugel
https://en.wikipedia.org/wiki/Dominique_Thomas
https://en.wikipedia.org/wiki/Marilou_Lopes-Benites
https://en.wikipedia.org/wiki/Lola_Giovannetti
https://en.wikipedia.org/wiki/Isabelle_Lapouge
https://en.wikipedia.org/wiki/Suzanne_Foulquier
https://en.wikipedia.org/wiki/Laure_Lapeyre
https://en.wikipedia.org/wiki/Chandra_Malatitch
https://en.wikipedia.org/wiki/John_Jesus_Romão
https://en.wikipedia.org/wiki/Ivo_Barroso
https://en.wikipedia.org/wiki/Gonçalo_Ferreira_De_Almeida
https://en.wikipedia.org/wiki/Miguel_Loureiro
https://en.wikipedia.org/wiki/Francisco_Peres
https://en.wikipedia.org/wiki/Fernando_Santos
https://en.wikipedia.org/wiki/Cindy_Scrash
https://en.wikipedia.org/wiki/Jenni_La_Rue
https://en.wikipedia.org/wiki/Gonçalo_Mendes
https://en.wikipedia.org/wiki/Derek_Graf
https://en.wikipedia.org/wiki/Justin_Price
https://en.wikipedia.org/wiki/Victory_Van_Tuyl
https://en.wikipedia.org/wiki/Michelle_Sebek
https://en.wikipedia.org/wiki/Christina_Klein
https://en.wikipedia.org/wiki/Amir_Kovacs
https://en.wikipedia.org/wiki/Shaun_Michael_Lynch
https://en.wikipedia.org/wiki/Lynn_McArthur
https://en.wikipedia.org/wiki/Jade_Moser
https://en.wikipedia.org/wiki/Kenneth_Vanbaeden
https://en.wikipedia.org/wiki/Valentijn_Dhaenens
https://en.wikipedia.org/wiki/Bert_Haelvoet
https://en.wikipedia.org/wiki/Gilda_De_Bal
https://en.wikipedia.org/wiki/Natali_Broods
https://en.wikipedia.org/wiki/Sofie_Palmers
https://en.wikipedia.org/wiki/Jos_Geens
https://en.wikipedia.org/wiki/Charlotte_Vandermeersch
https://en.wikipedia.org/wiki/Emilie_Cozette
https://en.wikipedia.org/wiki/Aurélie_Dupont
https://en.wikipedia.org/wiki/Dorothée_Gilbert
https://en.wikipedia.org/wiki/Marie-Agnès_Gillot
https://en.wikipedia.org/wiki/Agnès_Letestu
https://en.wikipedia.org/wiki/Delphine_Moussin
https://en.wikipedia.org/wiki/Kader_Belarbi
https://en.wikipedia.org/wiki/Claire-Marie_Osta
https://en.wikipedia.org/wiki/Lætitia_Pujol
https://en.wikipedia.org/wiki/Jérémie_Belingard
https://en.wikipedia.org/wiki/Mathieu_Ganio
https://en.wikipedia.org/wiki/Manuel_Legris
https://en.wikipedia.org/wiki/José_Martinez
https://en.wikipedia.org/wiki/Hervé_Moreau
https://en.wikipedia.org/wiki/Benjamin_Puech
https://en.wikipedia.org/wiki/Wilfried_Romoli
https://en.wikipedia.org/wiki/Marnie_Blok
https://en.wikipedia.org/wiki/Manuel_Broekman
https://en.wikipedia.org/wiki/Lidewij_Mahler
https://en.wikipedia.org/wiki/Evert_van_der_Meulen
https://en.wikipedia.org/wiki/Wieger_Windhorst
https://en.wikipedia.org/wiki/Anna_Khodush
https://en.wikipedia.org/wiki/Tina_Kandelaki
https://en.wikipedia.org/wiki/Valeri_Guryev
https://en.wikipedia.org/wiki/Andrey_Chubchenko
https://en.wikipedia.org/wiki/Vladimir_Panchik
https://en.wikipedia.org/wiki/Renee_Dai
https://en.wikipedia.org/wiki/Ella_Koon
https://en.wikipedia.org/wiki/Bruce_Law
https://en.wikipedia.org/wiki/Goon_Chung_Wong
https://en.wikipedia.org/wiki/Shareefa_Daanish
https://en.wikipedia.org/wiki/Ruly_Lubis
https://en.wikipedia.org/wiki/Daniel_Mananta
https://en.wikipedia.org/wiki/Imelda_Therinne
https://en.wikipedia.org/wiki/Sigi_Wimala
https://en.wikipedia.org/wiki/Edward_Baker-Duly
https://en.wikipedia.org/wiki/Derek_Riddell
https://en.wikipedia.org/wiki/Blerim_Destani
https://en.wikipedia.org/wiki/Gulliver_Page
https://en.wikipedia.org/wiki/Greg_Skipper
https://en.wikipedia.org/wiki/Steve_Daddow
https://en.wikipedia.org/wiki/Rene_Bowen
https://en.wikipedia.org/wiki/Robyn_Menzies
https://en.wikipedia.org/wiki/Ngoc_Phan
https://en.wikipedia.org/wiki/Louis_Okada
https://en.wikipedia.org/wiki/Koichi_Waki
https://en.wikipedia.org/wiki/Tomoki_Miyamoto
https://en.wikipedia.org/wiki/Laela_Sari
https://en.wikipedia.org/wiki/Yasushi_Asaya
https://en.wikipedia.org/wiki/Piet_Luan_Ta
https://en.wikipedia.org/wiki/Nik_Schodel
https://en.wikipedia.org/wiki/Nathan_Lawson
https://en.wikipedia.org/wiki/Ben_Seimer
https://en.wikipedia.org/wiki/Annette_van_Moorsel
https://en.wikipedia.org/wiki/Tanya_Crumel
https://en.wikipedia.org/wiki/Kevin_Kirk
https://en.wikipedia.org/wiki/Derek_J
https://en.wikipedia.org/wiki/Freddie_J
https://en.wikipedia.org/wiki/Jason_Griggers
https://en.wikipedia.org/wiki/Marvet_Britto
https://en.wikipedia.org/wiki/A'Lelia_Bundles
https://en.wikipedia.org/wiki/Andre_Harrell
https://en.wikipedia.org/wiki/Faheem_Najm
https://en.wikipedia.org/wiki/Мария_Бурова
https://en.wikipedia.org/wiki/Polina_Kutepova
https://en.wikipedia.org/wiki/Dean_Palinczuk
https://en.wikipedia.org/wiki/Rainer_Winkelvoß
https://en.wikipedia.org/wiki/Tony_Barger
https://en.wikipedia.org/wiki/Ana_Popescu
https://en.wikipedia.org/wiki/Albert_Gherasim
https://en.wikipedia.org/wiki/Rahman_Altın
https://en.wikipedia.org/wiki/Görkem_Yeltan
https://en.wikipedia.org/wiki/Nadir_Sarıbacak
https://en.wikipedia.org/wiki/Sonia_Vachon
https://en.wikipedia.org/wiki/Mylène_St-Sauveur
https://en.wikipedia.org/wiki/Élodie_Larivière
https://en.wikipedia.org/wiki/Catherine_Bérubé
https://en.wikipedia.org/wiki/Normand_Chouinard
https://en.wikipedia.org/wiki/Louise_Bombardier
https://en.wikipedia.org/wiki/Pierre-Luc_Lafontaine
https://en.wikipedia.org/wiki/René-Daniel_Dubois_
https://en.wikipedia.org/wiki/Jacques_Allard
https://en.wikipedia.org/wiki/Frances_Anderton
https://en.wikipedia.org/wiki/Michele_Di_Mauro
https://en.wikipedia.org/wiki/Giampiero_Judica
https://en.wikipedia.org/wiki/Deborah_Bernuzzi
https://en.wikipedia.org/wiki/Barbara_Braconi
https://en.wikipedia.org/wiki/Federica_Cassini
https://en.wikipedia.org/wiki/Sinead_Maguire
https://en.wikipedia.org/wiki/Misaki_Kuno
https://en.wikipedia.org/wiki/Sayaka_Ohara
https://en.wikipedia.org/wiki/Alex_Paez
https://en.wikipedia.org/wiki/Paola_Turbay
https://en.wikipedia.org/wiki/Tiffany_Hines
https://en.wikipedia.org/wiki/Brooke_Newton
https://en.wikipedia.org/wiki/Joe_Gerety
https://en.wikipedia.org/wiki/Anthony_Molinari
https://en.wikipedia.org/wiki/Chancellor_Miller
https://en.wikipedia.org/wiki/Natalie_R_Ridley
https://en.wikipedia.org/wiki/Brent_Falco
https://en.wikipedia.org/wiki/Preston_James_Hillier
https://en.wikipedia.org/wiki/Joey_Cape
https://en.wikipedia.org/wiki/Tim_Curran
https://en.wikipedia.org/wiki/Rick_DeVoe
https://en.wikipedia.org/wiki/Joe_Escalante
https://en.wikipedia.org/wiki/John_Feldmann
https://en.wikipedia.org/wiki/Lars_Frederiksen
https://en.wikipedia.org/wiki/Matt_Freeman
https://en.wikipedia.org/wiki/Greg_Graffin
https://en.wikipedia.org/wiki/Ryan_Greene
https://en.wikipedia.org/wiki/Mark_Hoppus
https://en.wikipedia.org/wiki/Philippe_Haussmann
https://en.wikipedia.org/wiki/Alexandre_Haussmann
https://en.wikipedia.org/wiki/Chris_Boyd
https://en.wikipedia.org/wiki/Karin_Bertling
https://en.wikipedia.org/wiki/Cecile_Anckarswärd
https://en.wikipedia.org/wiki/Rune_Bergman
https://en.wikipedia.org/wiki/Yoav_Donat
https://en.wikipedia.org/wiki/Dylan_Riley_Snyder
https://en.wikipedia.org/wiki/Hendrik_Toompere_Jr.
https://en.wikipedia.org/wiki/Harri_Kõrvits
https://en.wikipedia.org/wiki/Taavi_Teplenkov
https://en.wikipedia.org/wiki/Marika_Barabanstsikova
https://en.wikipedia.org/wiki/Liis_Lepik
https://en.wikipedia.org/wiki/Valeri_Fjodorov
https://en.wikipedia.org/wiki/Tarmo_Mitt
https://en.wikipedia.org/wiki/Moeno_Wakamatsu
https://en.wikipedia.org/wiki/Tõnu_Tepandi
https://en.wikipedia.org/wiki/Andres_Puustusmaa
https://en.wikipedia.org/wiki/Voldemar_Kendra
https://en.wikipedia.org/wiki/Arne_Otter
https://en.wikipedia.org/wiki/Leonhard_Kukats
https://en.wikipedia.org/wiki/Ivar_Hillep
https://en.wikipedia.org/wiki/Oleg_Pleanberg
https://en.wikipedia.org/wiki/Jaak_Müürsepp
https://en.wikipedia.org/wiki/Kristjan_Mändmaa
https://en.wikipedia.org/wiki/Aivar_Palu
https://en.wikipedia.org/wiki/Samantha_Siong_Facchi
https://en.wikipedia.org/wiki/Anthony_Marks
https://en.wikipedia.org/wiki/Billy_Magnussen
https://en.wikipedia.org/wiki/Patricia_Raven
https://en.wikipedia.org/wiki/Alissa_Dean
https://en.wikipedia.org/wiki/Maryam_Basir
https://en.wikipedia.org/wiki/Samantha_Hahn
https://en.wikipedia.org/wiki/Michael_M._Wartella
https://en.wikipedia.org/wiki/Russel_Lewis
https://en.wikipedia.org/wiki/Rich_Ceraulo
https://en.wikipedia.org/wiki/Garett_Stevens
https://en.wikipedia.org/wiki/Samantha_Jacober
https://en.wikipedia.org/wiki/Suzette_Gondry
https://en.wikipedia.org/wiki/Jean-Yves_Gondry
https://en.wikipedia.org/wiki/Michel_Gondry
https://en.wikipedia.org/wiki/Poppy_Miller
https://en.wikipedia.org/wiki/Jamie_Glover
https://en.wikipedia.org/wiki/Laura_Pyper
https://en.wikipedia.org/wiki/Amy_Loughton
https://en.wikipedia.org/wiki/Nathaniel_Gleed
https://en.wikipedia.org/wiki/Joshua_Jones
https://en.wikipedia.org/wiki/Liza_Sadovy
https://en.wikipedia.org/wiki/Eileen_O'Higgins
https://en.wikipedia.org/wiki/Sarah_Ovens
https://en.wikipedia.org/wiki/Lyla_Barrett-Rye
https://en.wikipedia.org/wiki/Teddy_Bunn
https://en.wikipedia.org/wiki/Susie_Trayling
https://en.wikipedia.org/wiki/Sarah_Gower
https://en.wikipedia.org/wiki/Claire_Gower
https://en.wikipedia.org/wiki/Joseph_Diaz
https://en.wikipedia.org/wiki/Max_Kidd
https://en.wikipedia.org/wiki/Zach_Freeman
https://en.wikipedia.org/wiki/Max_Fröhlich
https://en.wikipedia.org/wiki/Martin_Lindow
https://en.wikipedia.org/wiki/Anne_Houdy
https://en.wikipedia.org/wiki/Aarti_Mann
https://en.wikipedia.org/wiki/Jorge_Becerra
https://en.wikipedia.org/wiki/Javier_Oliván
https://en.wikipedia.org/wiki/Guillermo_Villegas
https://en.wikipedia.org/wiki/Joaquín_Rodríguez
https://en.wikipedia.org/wiki/Juan_Carlos_Torres
https://en.wikipedia.org/wiki/Fabian_Storniolo
https://en.wikipedia.org/wiki/Baltimore_Beltran
https://en.wikipedia.org/wiki/Ruben_Santiago
https://en.wikipedia.org/wiki/Ruben_Angelo
https://en.wikipedia.org/wiki/Pilar_Flynn
https://en.wikipedia.org/wiki/Emerald-Angel_Young

/tmp/ipykernel_334739/3212192908.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  acteurs_df_4['awards_info'] = acteurs_df_4['url_acteur'].apply(get_actor_awards_structured)

In [2]:
os.environ['AWS_S3_ENDPOINT']
S3_ENDPOINT_URL = 'http://' + os.environ['AWS_S3_ENDPOINT']
fs = s3fs.S3FileSystem(client_kwargs = {'endpoint_url' :S3_ENDPOINT_URL })
fs.ls('mlepennec-ensae')
BUCKET = 'mlepennec-ensae'
FILE_KEY_S3 = '/acteurs_df_1.csv'
FILE_PATH_S3 = BUCKET+FILE_KEY_S3
with fs.open(FILE_PATH_S3, mode = "rb") as file_in : 
    acteurs_df_1 = pd.read_csv(file_in,sep=',', header=0)

In [3]:
FILE_KEY_S3 = '/acteurs_df_2.csv'
FILE_PATH_S3 = BUCKET+FILE_KEY_S3
with fs.open(FILE_PATH_S3, mode = "rb") as file_in : 
    acteurs_df_2 = pd.read_csv(file_in,sep=',', header=0)

In [4]:
FILE_KEY_S3 = '/acteurs_df_3.csv'
FILE_PATH_S3 = BUCKET+FILE_KEY_S3
with fs.open(FILE_PATH_S3, mode = "rb") as file_in : 
    acteurs_df_3 = pd.read_csv(file_in,sep=',', header=0)

In [5]:
FILE_KEY_S3 = '/acteurs_df_4.csv'
FILE_PATH_S3 = BUCKET+FILE_KEY_S3
with fs.open(FILE_PATH_S3, mode = "rb") as file_in : 
    acteurs_df_4 = pd.read_csv(file_in,sep=',', header=0)

In [42]:
acteurs_df_concat = pd.concat([acteurs_df_1, acteurs_df_2, acteurs_df_3, acteurs_df_4], axis=0)

In [43]:
acteurs_df_concat=acteurs_df_concat.reset_index(drop=True)
acteurs_df_concat

,acteur,url_acteur,awards_info
0,Gerard Butler,https://en.wikipedia.org/wiki/Gerard_Butler,"[{'year': '2004', 'award': 'Dear Frankie', 're..."
1,Aaron Eckhart,https://en.wikipedia.org/wiki/Aaron_Eckhart,"[{'year': None, 'award': 'Independent Spirit A..."
2,Angela Bassett,https://en.wikipedia.org/wiki/Angela_Bassett,"[{'year': '1994', 'award': 'Best Actress', 're..."
3,Morgan Freeman,https://en.wikipedia.org/wiki/Morgan_Freeman,"[{'year': '1988', 'award': 'Best Supporting Ac..."
4,Radha Mitchell,https://en.wikipedia.org/wiki/Radha_Mitchell,"[{'year': '2001', 'award': 'Fangoria Chainsaw ..."
...,...,...,...
180640,Hebe Beardsall,https://en.wikipedia.org/wiki/Hebe_Beardsall,[]
180641,Lara Peake,https://en.wikipedia.org/wiki/Lara_Peake,[]
180642,David McCarrison,https://en.wikipedia.org/wiki/David_McCarrison,[]
180643,Alice Sanders,https://en.wikipedia.org/wiki/Alice_Sanders,[]
180644,Mikko Makela,https://en.wikipedia.org/wiki/Mikko_Makela,[]

In [46]:
acteurs_df_concat['awards_info'] = acteurs_df_concat['awards_info'].apply(ast.literal_eval)

In [79]:
df_avec_recompenses = acteurs_df_concat[acteurs_df_concat['awards_info'].apply(lambda x: x != [])].reset_index(drop=True)
df_avec_recompenses

,acteur,url_acteur,awards_info
0,Gerard Butler,https://en.wikipedia.org/wiki/Gerard_Butler,"[{'year': '2004', 'award': 'Dear Frankie', 're..."
1,Aaron Eckhart,https://en.wikipedia.org/wiki/Aaron_Eckhart,"[{'year': None, 'award': 'Independent Spirit A..."
2,Angela Bassett,https://en.wikipedia.org/wiki/Angela_Bassett,"[{'year': '1994', 'award': 'Best Actress', 're..."
3,Morgan Freeman,https://en.wikipedia.org/wiki/Morgan_Freeman,"[{'year': '1988', 'award': 'Best Supporting Ac..."
4,Radha Mitchell,https://en.wikipedia.org/wiki/Radha_Mitchell,"[{'year': '2001', 'award': 'Fangoria Chainsaw ..."
...,...,...,...
9593,Hannah Pearl Utt,https://en.wikipedia.org/wiki/Hannah_Pearl_Utt,"[{'year': '2009', 'award': 'Streamy Awards', '..."
9594,Alec Secareanu,https://en.wikipedia.org/wiki/Alec_Secareanu,"[{'year': 'British Independent Film Awards', '..."
9595,Patsy Ferran,https://en.wikipedia.org/wiki/Patsy_Ferran,"[{'year': '2014', 'award': 'Critics’ Circle Th..."
9596,André Aciman,https://en.wikipedia.org/wiki/André_Aciman,"[{'year': None, 'award': '1995 Whiting Award',..."
9597,Karyn Kusama,https://en.wikipedia.org/wiki/Karyn_Kusama,"[{'year': '2000', 'award': 'Girlfight', 'resul..."

In [76]:
url_wikipedia_en = "https://en.wikipedia.org/wiki/"
df_avec_recompenses['awards_info_2'] = df_avec_recompenses['url_acteur'].apply(get_actor_awards_structured)

https://en.wikipedia.org/wiki/Gerard_Butler
https://en.wikipedia.org/wiki/Aaron_Eckhart
https://en.wikipedia.org/wiki/Angela_Bassett
https://en.wikipedia.org/wiki/Morgan_Freeman
https://en.wikipedia.org/wiki/Radha_Mitchell
https://en.wikipedia.org/wiki/Dylan_McDermott
https://en.wikipedia.org/wiki/Melissa_Leo
https://en.wikipedia.org/wiki/Cole_Hauser
https://en.wikipedia.org/wiki/Robert_Forster
https://en.wikipedia.org/wiki/Ashley_Judd
https://en.wikipedia.org/wiki/Shivani_Ghai
https://en.wikipedia.org/wiki/Werner_Nekes
https://en.wikipedia.org/wiki/Joachim_Fuchsberger
https://en.wikipedia.org/wiki/Jonathan_Tucker
https://en.wikipedia.org/wiki/Jaime_Pressly
https://en.wikipedia.org/wiki/Barry_Bostwick
https://en.wikipedia.org/wiki/Jason_Alexander
https://en.wikipedia.org/wiki/Martin_Short
https://en.wikipedia.org/wiki/Bobby_Lockwood
https://en.wikipedia.org/wiki/Jeff_Bennett
https://en.wikipedia.org/wiki/Jodi_Benson
https://en.wikipedia.org/wiki/Jeff_Daniels
https://en.wikipedia.org/wiki/Joely_Richardson
https://en.wikipedia.org/wiki/John_Cena
https://en.wikipedia.org/wiki/Aidan_Gillen
https://en.wikipedia.org/wiki/Brian_J._White
https://en.wikipedia.org/wiki/Chelsey_Reist
https://en.wikipedia.org/wiki/Ty_Olsson
https://en.wikipedia.org/wiki/Adah_Sharma
https://en.wikipedia.org/wiki/Rajendranath_Zutshi
https://en.wikipedia.org/wiki/Indraneil_Sengupta
https://en.wikipedia.org/wiki/Tia_Bajpai
https://en.wikipedia.org/wiki/Vidya_Malvade
https://en.wikipedia.org/wiki/Sharad_Kelkar
https://en.wikipedia.org/wiki/Julie_Delpy
https://en.wikipedia.org/wiki/Daniel_Brühl
https://en.wikipedia.org/wiki/Dylan_Baker
https://en.wikipedia.org/wiki/Chris_Rock
https://en.wikipedia.org/wiki/Vincent_Gallo
https://en.wikipedia.org/wiki/Malinda_Williams
https://en.wikipedia.org/wiki/Carmen_Lopez
https://en.wikipedia.org/wiki/Robert_Englund
https://en.wikipedia.org/wiki/Lin_Shaye
https://en.wikipedia.org/wiki/Brendan_McCarthy
https://en.wikipedia.org/wiki/Toshiaki_Karasawa
https://en.wikipedia.org/wiki/Takako_Tokiwa
https://en.wikipedia.org/wiki/Teruyuki_Kagawa
https://en.wikipedia.org/wiki/Kuranosuke_Sasaki
https://en.wikipedia.org/wiki/Kanji_Tsuda
https://en.wikipedia.org/wiki/Airi_Taira
https://en.wikipedia.org/wiki/Naoto_Takenaka
https://en.wikipedia.org/wiki/Arata_Furuta
https://en.wikipedia.org/wiki/Cillian_Murphy
https://en.wikipedia.org/wiki/Leo_Bill
https://en.wikipedia.org/wiki/Imogen_Poots
https://en.wikipedia.org/wiki/Robert_Carlyle
https://en.wikipedia.org/wiki/Rose_Byrne
https://en.wikipedia.org/wiki/Jeremy_Renner
https://en.wikipedia.org/wiki/Harold_Perrineau
https://en.wikipedia.org/wiki/Idris_Elba
https://en.wikipedia.org/wiki/Matt_Reeves
https://en.wikipedia.org/wiki/André_Dussollier
https://en.wikipedia.org/wiki/Michel_Boujenah
https://en.wikipedia.org/wiki/Annick_Alane
https://en.wikipedia.org/wiki/Fiona_Shaw
https://en.wikipedia.org/wiki/Patrick_Kilpatrick
https://en.wikipedia.org/wiki/Donal_Logue
https://en.wikipedia.org/wiki/Danuel_Pipoly
https://en.wikipedia.org/wiki/Jim_Varney
https://en.wikipedia.org/wiki/Lindsay_Felton
https://en.wikipedia.org/wiki/Josh_Hartnett
https://en.wikipedia.org/wiki/Danny_Huston
https://en.wikipedia.org/wiki/Thomas_Newman
https://en.wikipedia.org/wiki/John_Rawls
https://en.wikipedia.org/wiki/Katharine_Isabelle
https://en.wikipedia.org/wiki/Lena_Headey
https://en.wikipedia.org/wiki/Dominic_West
https://en.wikipedia.org/wiki/David_Wenham
https://en.wikipedia.org/wiki/Stephen_McHattie
https://en.wikipedia.org/wiki/Eva_Green
https://en.wikipedia.org/wiki/George_Georgiou
https://en.wikipedia.org/wiki/Steven_Cree
https://en.wikipedia.org/wiki/Annette_O'Toole
https://en.wikipedia.org/wiki/James_Remar
https://en.wikipedia.org/wiki/Jonathan_Banks
https://en.wikipedia.org/wiki/Tisha_Campbell-Martin
https://en.wikipedia.org/wiki/Bernie_Casey
https://en.wikipedia.org/wiki/Chris_Bauer
https://en.wikipedia.org/wiki/Norman_Reedus
https://en.wikipedia.org/wiki/Johnathon_Schaech
https://en.wikipedia.org/wiki/Julie_Benz
https://en.wikipedia.org/wiki/Jim_Metzler
https://en.wikipedia.org/wiki/J.J._Johnston
https://en.wikipedia.org/wiki/Mickey_Rourke
https://en.wikipedia.org/wiki/Dougray_Scott
https://en.wikipedia.org/wiki/Ti_Lung
https://en.wikipedia.org/wiki/Chow_Yun-fat
https://en.wikipedia.org/wiki/Leslie_Cheung
https://en.wikipedia.org/wiki/Kenneth_Tsang
https://en.wikipedia.org/wiki/Tsui_Hark

/tmp/ipykernel_511110/649594576.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_avec_recompenses['awards_info_2'] = df_avec_recompenses['url_acteur'].apply(get_actor_awards_structured)

In [77]:
df_avec_recompenses

,acteur,url_acteur,awards_info,awards_info_2
0,Gerard Butler,https://en.wikipedia.org/wiki/Gerard_Butler,"[{'year': '2004', 'award': 'Dear Frankie', 're...","[{'year': '2004', 'award': 'Dear Frankie', 're..."
1,Aaron Eckhart,https://en.wikipedia.org/wiki/Aaron_Eckhart,"[{'year': None, 'award': 'Independent Spirit A...","[{'year': None, 'award': 'Independent Spirit A..."
2,Angela Bassett,https://en.wikipedia.org/wiki/Angela_Bassett,"[{'year': '1994', 'award': 'Best Actress', 're...","[Page des awards, {'year': '1994', 'award': 'B..."
3,Morgan Freeman,https://en.wikipedia.org/wiki/Morgan_Freeman,"[{'year': '1988', 'award': 'Best Supporting Ac...","[Page des awards, {'year': '1988', 'award': 'B..."
4,Radha Mitchell,https://en.wikipedia.org/wiki/Radha_Mitchell,"[{'year': '2001', 'award': 'Fangoria Chainsaw ...","[{'year': '2001', 'award': 'Fangoria Chainsaw ..."
5,Dylan McDermott,https://en.wikipedia.org/wiki/Dylan_McDermott,"[{'year': '1998', 'award': 'Viewers for Qualit...","[{'year': '1998', 'award': 'Viewers for Qualit..."
6,Melissa Leo,https://en.wikipedia.org/wiki/Melissa_Leo,"[{'year': '1985', 'award': 'Daytime Emmy Award...","[{'year': '1985', 'award': 'Daytime Emmy Award..."
7,Cole Hauser,https://en.wikipedia.org/wiki/Cole_Hauser,"[{'year': '2001', 'award': 'Independent Spirit...","[{'year': '2001', 'award': 'Independent Spirit..."
8,Robert Forster,https://en.wikipedia.org/wiki/Robert_Forster,"[{'year': 'Academy Awards', 'award': '1998', '...","[{'year': 'Academy Awards', 'award': '1998', '..."
9,Ashley Judd,https://en.wikipedia.org/wiki/Ashley_Judd,"[{'year': '1993', 'award': 'Ruby in Paradise',...","[{'year': '1993', 'award': 'Ruby in Paradise',..."
10,Shivani Ghai,https://en.wikipedia.org/wiki/Shivani_Ghai,"[{'year': '2013', 'award': 'British Soap Award...","[{'year': '2013', 'award': 'British Soap Award..."
11,Werner Nekes,https://en.wikipedia.org/wiki/Werner_Nekes,"[{'year': None, 'award': '1969: Bambi Awards f...","[{'year': None, 'award': '1969: Bambi Awards f..."
12,Joachim Fuchsberger,https://en.wikipedia.org/wiki/Joachim_Fuchsberger,"[{'year': '1942', 'award': 'War Merit Cross 2n...","[{'year': '1942', 'award': 'War Merit Cross 2n..."
13,Jonathan Tucker,https://en.wikipedia.org/wiki/Jonathan_Tucker,"[{'year': '2000', 'award': 'Young Artist Award...","[{'year': '2000', 'award': 'Young Artist Award..."
14,Jaime Pressly,https://en.wikipedia.org/wiki/Jaime_Pressly,"[{'year': '2002', 'award': 'MTV Movie & TV Awa...","[{'year': '2002', 'award': 'MTV Movie & TV Awa..."
15,Barry Bostwick,https://en.wikipedia.org/wiki/Barry_Bostwick,"[{'year': '1972', 'award': 'Tony Awards', 'res...","[{'year': '1972', 'award': 'Tony Awards', 'res..."
16,Jason Alexander,https://en.wikipedia.org/wiki/Jason_Alexander,"[{'year': 'Daytime Emmy Awards', 'award': '202...","[{'year': 'Daytime Emmy Awards', 'award': '202..."
17,Martin Short,https://en.wikipedia.org/wiki/Martin_Short,"[{'year': '1983', 'award': 'Outstanding Writin...","[Page des awards, {'year': '1983', 'award': 'O..."
18,Bobby Lockwood,https://en.wikipedia.org/wiki/Bobby_Lockwood,"[{'year': '2013', 'award': 'British Academy Ch...","[{'year': '2013', 'award': 'British Academy Ch..."
19,Jeff Bennett,https://en.wikipedia.org/wiki/Jeff_Bennett,"[{'year': '1997', 'award': 'Annie Awards', 're...","[{'year': '1997', 'award': 'Annie Awards', 're..."
20,Jodi Benson,https://en.wikipedia.org/wiki/Jodi_Benson,"[{'year': '1992', 'award': 'Tony Award', 'resu...","[{'year': '1992', 'award': 'Tony Award', 'resu..."
21,Jeff Daniels,https://en.wikipedia.org/wiki/Jeff_Daniels,"[{'year': 'Golden Globe Awards', 'award': '198...","[{'year': 'Golden Globe Awards', 'award': '198..."
22,Joely Richardson,https://en.wikipedia.org/wiki/Joely_Richardson,"[{'year': '1999', 'award': 'Independent Spirit...","[{'year': '1999', 'award': 'Independent Spirit..."
23,John Cena,https://en.wikipedia.org/wiki/John_Cena,"[{'year': '2017', 'award': 'CinemaCon', 'resul...","[{'year': '2017', 'award': 'CinemaCon', 'resul..."
24,Aidan Gillen,https://en.wikipedia.org/wiki/Aidan_Gillen,"[{'year': '2000', 'award': 'Queer as Folk', 'r...","[{'year': '2000', 'award': 'Queer as Folk', 'r..."
25,Brian J. White,https://en.wikipedia.org/wiki/Brian_J._White,"[{'year': '2019', 'award': 'Daytime Emmy Award...","[{'year': '2019', 'award': 'Daytime Emmy Award..."
26,Chelsey Reist,https://en.wikipedia.org/wiki/Chelsey_Reist,"[{'year': '2019', 'award': 'Leo Awards', 'resu...","[{'year': '2019', 'award': 'Leo Awards', 'resu..."
27,Ty Olsson,https://en.wikipedia.org/wiki/Ty_Olsson,"[{'year': '2016', 'award': 'UBCP/ACTRA Awards'...","[{'year': '2016', 'award': 'UBCP/ACTRA Awards'..."
28,Adah Sharma,https://en.wikipedia.org/wiki/Adah_Sharma,"[{'year': '2009', 'award': 'Screen Awards', 'r...","[{'year': '2009', 'award': 'Screen Awards', 'r..."
29,Rajendranath Zutshi,https://en.wikipedia.org/wiki/Rajendranath_Zutshi,"[{'year': '2002', 'award': 'Indian Telly Award...","[{'year': '2002', 'award': 'Indian Telly Award..."
30,Indraneil Sengupta,https://en.wikipedia.org/wiki/Indraneil_Sengupta,"[{'year': None, 'award': '2008 - ITA Award for...","[{'year': None, 'award': '2008 - ITA Award for..."
31,Tia Bajpai,https://en.wikipedia.org/wiki/Tia_Bajpai,"[{'year': '4th Mirchi Music Awards', 'award': ...","[{'year': '4th Mirchi Music Awards', 'award': ..."
32,Vidya Malvade,https://en.wikipedia.org/wiki/Vidya_Malvade,"[{'year': '2004', 'award': 'Inteha', 'result':...","[{'year': '2004', 'award': 'Inteha', 'result':..."
33,Sharad Kelkar,https://en.wikipedia.org/wiki/Sharad_Kelkar,"[{'year': '2010', 'award': 'Gold Awards for Be...","[{'year': '2010', 'award': 'Gold Awards for Be..."
34,Julie Delpy,https://en.wikipedia.org/wiki/Julie_Delpy,"[{'year': '1987', 'award': 'César Award', 'res...","[{'year': '1987', 'award': 'César Award', 'res..."
35,Daniel Brühl,https://en.wikipedia.org/wiki/Daniel_Brühl,"[{'year': '2002', 'award': 'Bavarian Film Awar...","[{'year': '2002', 'award': 'Bavarian Film Awar..."
36,Dylan Baker,https://en.wikipedia.org/wiki/Dylan_Baker,"[{'year': '1991', 'award': 'Tony Award', 'resu...","[{'year': '1991', 'award': 'Tony Award', 'resu..."
37,Chris Rock,https://en.wikipedia.org/wiki/Chris_Rock,"[{'year': '1997', 'award': 'Outstanding Variet...","[Page des awards, {'year': '1997', 'award': 'O..."
38,Vincent Gallo,https://en.wikipedia.org/wiki/Vincent_Gallo,"[{'year': '1998', 'award': 'Deauville Film Fes...","[{'year': '1998', 'award': 'Deauville Film Fes..."
39,Malinda Williams,https://en.wikipedia.org/wiki/Malinda_Williams,"[{'year': '2000', 'award': 'Black Reel Awards'...","[{'year': '2000', 'award': 'Black Reel Awards'..."
40,Carmen Lopez,https://en.wikipedia.org/wiki/Carmen_Lopez,"[{'year': 'ALMA Awards', 'award': '2006', 'res...","[{'year': 'ALMA Awards', 'award': '2006', 'res..."
41,Robert Englund,https://en.wikipedia.org/wiki/Robert_Englund,"[{'year': '1988', 'award': 'Saturn Award', 're...","[{'year': '1988', 'award': 'Saturn Award', 're..."
42,Lin Shaye,https://en.wikipedia.org/wiki/Lin_Shaye,"[{'year': '1999', 'award': 'Blockbuster Entert...","[{'year': '1999', 'award': 'Blockbuster Entert..."
43,Brendan McCarthy,https://en.wikipedia.org/wiki/Brendan_McCarthy,"[{'year': None, 'award': '1992: nominated for ...","[{'year': None, 'award': '1992: nominated for ..."
44,Toshiaki Karasawa,https://en.wikipedia.org/wiki/Toshiaki_Karasawa,"[{'year': '1992', 'award': '65th Kinema Junpo ...","[{'year': '1992', 'award': '65th Kinema Junpo ..."
45,Takako Tokiwa,https://en.wikipedia.org/wiki/Takako_Tokiwa,"[{'year': None, 'award': '20th Elan d'or Award...","[{'year': None, 'award': '20th Elan d'or Award..."
46,Teruyuki Kagawa,https://en.wikipedia.org/wiki/Teruyuki_Kagawa,"[{'year': None, 'award': 'Teruyuki Kagawa was ...","[{'year': None, 'award': 'Teruyuki Kagawa was ..."
47,Kuranosuke Sasaki,https://en.wikipedia.org/wiki/Kuranosuke_Sasaki,"[{'year': None, 'award': '2015 the 38th Japan ...","[{'year': None, 'award': '2015 the 38th Japan ..."
48,Kanji Tsuda,https://en.wikipedia.org/wiki/Kanji_Tsuda,"[{'year': '2002: 45th Blue Ribbon Awards', 'aw...","[{'year': '2002: 45th Blue Ribbon Awards', 'aw..."
49,Airi Taira,https://en.wikipedia.org/wiki/Airi_Taira,"[{'year': None, 'award': '33rd Japan Academy P...","[{'year': None, 'award': '33rd Japan Academy P..."
50,Naoto Takenaka,https://en.wikipedia.org/wiki/Naoto_Takenaka,"[{'year': None, 'award': '1991', 'result': Non...","[{'year': None, 'award': '1991', 'result': Non..."
51,Arata Furuta,https://en.wikipedia.org/wiki/Arata_Furuta,"[{'year': '2021', 'award': '46th Hochi Film Aw...","[{'year': '2021', 'award': '46th Hochi Film Aw..."
52,Cillian Murphy,https://en.wikipedia.org/wiki/Cillian_Murphy,"[{'year': '2024', 'award': 'Best Actor', 'resu...","[Page des awards, {'year': '2024', 'award': 'B..."
53,Leo Bill,https://en.wikipedia.org/wiki/Leo_Bill,"[{'year': '2006', 'award': 'Fantastic Fest', '...","[{'year': '2006', 'award': 'Fantastic Fest', '..."
54,Imogen Poots,https://en.wikipedia.org/wiki/Imogen_Poots,"[{'year': '2007', 'award': 'British Independen...","[{'year': '2007', 'award': 'British Independen..."
55,Robert Carlyle,https://en.wikipedia.org/wiki/Robert_Carlyle,"[{'year': '1993', 'award': 'BAFTA Scotland Awa...","[{'year': '1993', 'award': 'BAFTA Scotland Awa..."
56,Rose Byrne,https://en.wikipedia.org/wiki/Rose_Byrne,"[{'year': 'AACTA Awards', 'award': '2014', 're...","[{'year': 'AACTA Awards', 'award': '2014', 're..."
57,Jeremy Renner,https://en.wikipedia.org/wiki/Jeremy_Renner,"[{'year': '2010', 'award': 'The Hurt Locker', ...","[Page des awards, {'year': '2010', 'award': 'T..."
58,Harold Perrineau,https://en.wikipedia.org/wiki/Harold_Perrineau,"[{'year': '1996', 'award': 'Independent Spirit...","[{'year': '1996', 'award': 'Independent Spirit..."
59,Idris Elba,https://en.wikipedia.org/wiki/Idris_Elba,"[{'year': '2015', 'award': 'Best Actor in a Su...","[Page des awards, {'year': '2015', 'award': 'B..."
60,Matt Reeves,https://en.wikipedia.org/wiki/Matt_Reeves,"[{'year': '2008', 'award': 'Saturn Awards', 'r...","[{'year': '2008', 'award': 'Saturn Awards', 'r..."
61,André Dussollier,https://en.wikipedia.org/wiki/André_Dussollier,"[{'year': '1993', 'award': 'César Awards', 're...","[{'year': '1993', 'award': 'César Awards', 're..."
62,Michel Boujenah,https://en.wikipedia.org/wiki/Michel_Boujenah,"[{'year': '1985', 'award': 'won the César Awar...","[{'year': '1985', 'award': 'won the César Awar..."
63,Annick Alane,https://en.wikipedia.org/wiki/Annick_Alane,"[{'year': '1993: Nomination', 'award': 'Molièr...","[{'year': '1993: Nomination', 'award': 'Molièr..."
64,Fiona Shaw,https://en.wikipedia.org/wiki/Fiona_Shaw,"[{'year': '1986', 'award': 'Society of London ...","[{'year': '1986', 'award': 'Society of London ..."
65,Patrick Kilpatrick,https://en.wikipedia.org/wiki/Patrick_Kilpatrick,"[{'year': '2019', 'award': 'Dreamachine Intern...","[{'year': '2019', 'award': 'Dreamachine Intern..."
66,Donal Logue,https://en.wikipedia.org/wiki/Donal_Logue,"[{'year': 'Ashland Independent Film Festival',...","[{'year': 'Ashland Independent Film Festival',..."
67,Danuel Pipoly,https://en.wikipedia.org/wiki/Danuel_Pipoly,"[{'year': '1991', 'award': 'Young Artist Award...","[{'year': '1991', 'award': 'Young Artist Award..."
68,Jim Varney,https://en.wikipedia.org/wiki/Jim_Varney,"[{'year': '1987', 'award': 'Ernest Goes to Cam...","[{'year': '1987', 'award': 'Ernest Goes to Cam..."
69,Lindsay Felton,https://en.wikipedia.org/wiki/Lindsay_Felton,"[{'year': '1995', 'award': 'Young Artist Award...","[{'year': '1995', 'award': 'Young Artist Award..."
70,Josh Hartnett,https://en.wikipedia.org/wiki/Josh_Hartnett,"[{'year': '1999', 'award': 'Blockbuster Entert...","[{'year': '1999', 'award': 'Blockbuster Entert..."
71,Danny Huston,https://en.wikipedia.org/wiki/Danny_Huston,"[{'year': 'Chlotrudis Awards', 'award': '2007'...","[{'year': 'Chlotrudis Awards', 'award': '2007'..."
72,Thomas Newman,https://en.wikipedia.org/wiki/Thomas_Newman,"[{'year': '1995', 'award': 'Best Original Scor...","[Page des awards, {'year': '1995', 'award': 'B..."
73,John Rawls,https://en.wikipedia.org/wiki/John_Rawls,"[{'year': None, 'award': 'Bronze Star for radi...","[{'year': None, 'award': 'Bronze Star for radi..."
74,Katharine Isabelle,https://en.wikipedia.org/wiki/Katharine_Isabelle,"[{'year': '2002', 'award': 'Ginger Snaps Turni...","[{'year': '2002', 'award': 'Ginger Snaps Turni..."
75,Lena Headey,https://en.wikipedia.org/wiki/Lena_Headey,"[{'year': '2001', 'award': 'Silver Iris Award'...","[{'year': '2001', 'award': 'Silver Iris Award'..."
76,Dominic West,https://en.wikipedia.org/wiki/Dominic_West,"[{'year': '2002', 'award': 'Critics' Choice Mo...","[{'year': '2002', 'award': 'Critics' Choice Mo..."
77,David Wenham,https://en.wikipedia.org/wiki/David_Wenham,[{'year': 'Australian Film Institute Award for...,[{'year': 'Australian Film Institute Award for...
78,Stephen McHattie,https://en.wikipedia.org/wiki/Stephen_McHattie,"[{'year': None, 'award': '1995: Gemini Award f...","[{'year': None, 'award': '1995: Gemini Award f..."
79,Eva Green,https://en.wikipedia.org/wiki/Eva_Green,"[{'year': 'British Academy Film Awards', 'awar...","[{'year': 'British Academy Film Awards', 'awar..."
80,George Georgiou,https://en.wikipedia.org/wiki/George_Georgiou,"[{'year': None, 'award': 'World Press Photo : ...","[{'year': None, 'award': 'World Press Photo : ..."
81,Steven Cree,https://en.wikipedia.org/wiki/Steven_Cree,"[{'year': '2019', 'award': 'Omaha Film Festiva...","[{'year': '2019', 'award': 'Omaha Film Festiva..."
82,Annette O'Toole,https://en.wikipedia.org/wiki/Annette_O'Toole,"[{'year': '1984', 'award': 'Saturn Awards', 'r...","[{'year': '1984', 'award': 'Saturn Awards', 'r..."
83,James Remar,https://en.wikipedia.org/wiki/James_Remar,"[{'year': '2007', 'award': 'Saturn Award', 're...","[{'year': '2007', 'award': 'Saturn Award', 're..."
84,Jonathan Banks,https://en.wikipedia.org/wiki/Jonathan_Banks,"[{'year': '2013', 'award': 'Critics' Choice Te...","[{'year': '2013', 'award': 'Critics' Choice Te..."
85,Tisha Campbell-Martin,https://en.wikipedia.org/wiki/Tisha_Campbell-M...,"[{'year': '1991', 'award': 'Independent Spirit...","[{'year': '1991', 'award': 'Independent Spirit..."
86,Bernie Casey,https://en.wikipedia.org/wiki/Bernie_Casey,"[{'year': 'NAACP Image Award', 'award': '1974'...","[{'year': 'NAACP Image Award', 'award': '1974'..."
87,Chris Bauer,https://en.wikipedia.org/wiki/Chris_Bauer,"[{'year': '2009', 'award': '14th Satellite Awa...","[{'year': '2009', 'award': '14th Satellite Awa..."
88,Norman Reedus,https://en.wikipedia.org/wiki/Norman_Reedus,"[{'year': '1997', 'award': 'New England Film &...","[{'year': '1997', 'award': 'New England Film &..."
89,Johnathon Schaech,https://en.wikipedia.org/wiki/Johnathon_Schaech,"[{'year': '2007', 'award': 'Phoenix Film Festi...","[{'year': '2007', 'award': 'Phoenix Film Festi..."
90,Julie Benz,https://en.wikipedia.org/wiki/Julie_Benz,"[{'year': '2006', 'award': '11th Satellite Awa...","[{'year': '2006', 'award': '11th Satellite Awa..."
91,Jim Metzler,https://en.wikipedia.org/wiki/Jim_Metzler,"[{'year': '1983', 'award': '40th Golden Globe ...","[{'year': '1983', 'award': '40th Golden Globe ..."
92,J.J. Johnston,https://en.wikipedia.org/wiki/J.J._Johnston,"[{'year': None, 'award': '1983-84 New York The...","[{'year': None, 'award': '1983-84 New York The..."
93,Mickey Rourke,https://en.wikipedia.org/wiki/Mickey_Rourke,"[{'year': '1983', 'award': 'Boston Society of ...","[{'year': '1983', 'award': 'Boston Society of ..."
94,Dougray Scott,https://en.wikipedia.org/wiki/Dougray_Scott,"[{'year': '1999', 'award': 'Teen Choice Awards...","[{'year': '1999', 'award': 'Teen Choice Awards..."
95,Ti Lung,https://en.wikipedia.org/wiki/Ti_Lung,"[{'year': '1973', 'award': '11th Golden Horse ...","[{'year': '1973', 'award': '11th Golden Horse ..."
96,Chow Yun-fat,https://en.wikipedia.org/wiki/Chow_Yun-fat,[{'year': 'Hong Kong Academy for Performing Ar...,[{'year': 'Hong Kong Academy for Performing Ar...
97,Leslie Cheung,https://en.wikipedia.org/wiki/Leslie_Cheung,"[{'year': '1984', 'award': 'Top 10 Gold Songs'...","[{'year': '1984', 'award': 'Top 10 Gold Songs'..."
98,Kenneth Tsang,https://en.wikipedia.org/wiki/Kenneth_Tsang,"[{'year': '1999', 'award': 'Star Awards', 'res...","[{'year': '1999', 'award': 'Star Awards', 'res..."
99,Tsui Hark,https://en.wikipedia.org/wiki/Tsui_Hark,"[{'year': '1981', 'award': 'Best Director', 'r...","[{'year': '1981', 'award': 'Best Director', 'r..."

In [78]:
df_avec_recompenses.iloc[3,3]

['Page des awards',
 {'year': '1988',
  'award': 'Best Supporting Actor',
  'result': 'Street Smart',
  'project': 'Nominated'},
 {'year': '1990',
  'award': 'Best Actor',
  'result': 'Driving Miss Daisy',
  'project': 'Nominated'},
 {'year': '1995',
  'award': 'The Shawshank Redemption',
  'result': 'Nominated',
  'project': '[ 3 ]'},
 {'year': '2005',
  'award': 'Best Supporting Actor',
  'result': 'Million Dollar Baby',
  'project': 'Won'},
 {'year': '2010',
  'award': 'Best Actor',
  'result': 'Invictus',
  'project': 'Nominated'},
 {'year': '2016',
  'award': 'Outstanding Informational Series or Special',
  'result': 'The Story of God with Morgan Freeman',
  'project': 'Nominated'},
 {'year': '2018',
  'award': 'Outstanding Narrator',
  'result': 'March of the Penguins 2: The Next Step',
  'project': 'Nominated'},
 {'year': '2021',
  'award': 'Outstanding Guest Actor in a Comedy Series',
  'result': 'The Kominsky Method (episode: "The Round Toes, of the High Shoes")',
  'project': 'Nominated'},
 {'year': '2023',
  'award': 'Outstanding Narrator',
  'result': 'Our Universe (episode: "Chasing Starlight")',
  'project': 'Nominated'},
 {'year': '2024',
  'award': 'Life on Our Planet (episode: "The Rules of Life")',
  'result': 'Nominated',
  'project': '[ 10 ]'},
 {'year': '2012',
  'award': 'Outstanding Science and Technology Programming',
  'result': 'Through the Wormhole',
  'project': 'Nominated'},
 {'year': '1988',
  'award': 'Best Supporting Actor – Motion Picture',
  'result': 'Street Smart',
  'project': 'Nominated'},
 {'year': '1990',
  'award': 'Best Actor – Motion Picture Musical or Comedy',
  'result': 'Driving Miss Daisy',
  'project': 'Won'},
 {'year': '1995',
  'award': 'Best Actor – Motion Picture Drama',
  'result': 'The Shawshank Redemption',
  'project': 'Nominated'},
 {'year': '2005',
  'award': 'Best Supporting Actor – Motion Picture',
  'result': 'Million Dollar Baby',
  'project': 'Nominated'},
 {'year': '2010',
  'award': 'Best Actor – Motion Picture Drama',
  'result': 'Invictus',
  'project': 'Nominated'},
 {'year': '2012',
  'award': 'Cecil B. DeMille Award',
  'result': 'Recipient',
  'project': '[ 16 ]'},
 {'year': '1996',
  'award': 'Best Spoken Word Album for Children',
  'result': "Follow the Drinkin' Gourd",
  'project': 'Nominated'},
 {'year': '1995',
  'award': 'Outstanding Male Actor in a Leading Role',
  'result': 'The Shawshank Redemption',
  'project': 'Nominated'},
 {'year': '2005',
  'award': 'Outstanding Male Actor in a Supporting Role',
  'result': 'Million Dollar Baby',
  'project': 'Won'},
 {'year': '2010',
  'award': 'Outstanding Male Actor in a Leading Role',
  'result': 'Invictus',
  'project': 'Nominated'},
 {'year': '2017',
  'award': 'Screen Actors Guild Life Achievement Award',
  'result': 'Recipient',
  'project': '[ 21 ]'}]