In [1]:
import os
import pandas as pd
import s3fs
import sklearn

In [2]:
os.environ['AWS_S3_ENDPOINT']
S3_ENDPOINT_URL = 'http://' + os.environ['AWS_S3_ENDPOINT']
fs = s3fs.S3FileSystem(client_kwargs = {'endpoint_url' :S3_ENDPOINT_URL })
fs.ls('mlepennec-ensae')
BUCKET = 'mlepennec-ensae'
FILE_KEY_S3 = '/engieX.csv'
FILE_PATH_S3 = BUCKET+FILE_KEY_S3
with fs.open(FILE_PATH_S3, mode = "rb") as file_in : 
    X_df = pd.read_csv(file_in, index_col=0,sep=';')

In [3]:
X_df

,MAC_CODE,Date_time,Pitch_angle,Pitch_angle_min,Pitch_angle_max,Pitch_angle_std,Hub_temperature,Hub_temperature_min,Hub_temperature_max,Hub_temperature_std,...,Rotor_speed,Rotor_speed_min,Rotor_speed_max,Rotor_speed_std,Rotor_bearing_temperature,Rotor_bearing_temperature_min,Rotor_bearing_temperature_max,Rotor_bearing_temperature_std,Absolute_wind_direction_c,Nacelle_angle_c
ID,,,,,,,,,,,,,,,,,,,,,
1,WT3,1.0,92.470001,92.470001,92.470001,0.00,7.00,7.000000,7.0,0.00,...,0.000000,0.00,0.000000,0.00,2.400000,2.400000,2.400000,0.00,294.19000,294.23999
2,WT3,2.0,92.470001,92.470001,92.470001,0.00,7.00,7.000000,7.0,0.00,...,0.000000,0.00,0.000000,0.00,2.400000,2.400000,2.400000,0.00,297.82999,294.23999
3,WT3,3.0,92.470001,92.470001,92.470001,0.00,7.00,7.000000,7.0,0.00,...,0.000000,0.00,0.000000,0.00,2.400000,2.400000,2.400000,0.00,322.20999,294.23999
4,WT3,4.0,92.470001,92.470001,92.470001,0.00,6.97,6.700000,7.0,0.02,...,0.000000,0.00,0.000000,0.00,2.400000,2.400000,2.400000,0.00,318.69000,294.23999
5,WT3,5.0,92.470001,92.470001,92.470001,0.00,6.93,6.000000,7.0,0.17,...,0.000000,0.00,0.000000,0.00,2.400000,2.400000,2.500000,0.00,314.89001,294.23999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
617382,WT1,157676.0,-1.010000,-1.010000,-0.840000,0.01,18.00,17.090000,18.0,0.05,...,16.930000,14.79,17.379999,0.52,35.790001,35.700001,35.900002,0.02,229.27000,231.56000
617383,WT1,157677.0,-1.010000,-1.010000,-1.010000,0.00,17.99,17.469999,18.0,0.05,...,16.969999,15.39,17.389999,0.34,35.810001,35.599998,35.849998,0.06,227.53000,231.56000
617384,WT1,157678.0,-0.810000,-1.010000,1.490000,0.58,18.00,17.770000,18.0,0.01,...,17.040001,15.67,17.420000,0.30,36.060001,35.799999,36.099998,0.10,228.75000,231.56000
617385,WT1,157679.0,-1.000000,-1.010000,-0.620000,0.03,18.00,17.700001,18.0,0.01,...,16.860001,14.86,17.340000,0.60,36.189999,36.099998,36.200001,0.05,226.16000,231.56000
617386,WT1,157680.0,-0.910000,-1.010000,1.080000,0.42,18.00,18.000000,18.0,0.00,...,17.100000,16.17,17.389999,0.15,36.240002,36.200001,36.400002,0.06,226.06000,231.56000

In [4]:
X_WT1_df = X_df[X_df.MAC_CODE == 'WT1']
X_WT1_df

,MAC_CODE,Date_time,Pitch_angle,Pitch_angle_min,Pitch_angle_max,Pitch_angle_std,Hub_temperature,Hub_temperature_min,Hub_temperature_max,Hub_temperature_std,...,Rotor_speed,Rotor_speed_min,Rotor_speed_max,Rotor_speed_std,Rotor_bearing_temperature,Rotor_bearing_temperature_min,Rotor_bearing_temperature_max,Rotor_bearing_temperature_std,Absolute_wind_direction_c,Nacelle_angle_c
ID,,,,,,,,,,,,,,,,,,,,,
462680,WT1,1.0,92.410004,92.410004,92.410004,0.00,8.24,8.000000,9.0,0.28,...,0.000000,0.00,0.000000,0.00,2.380000,2.300000,2.500000,0.06,301.44000,302.89999
462681,WT1,2.0,92.410004,92.410004,92.410004,0.00,8.19,8.000000,9.0,0.37,...,0.000000,0.00,0.000000,0.00,2.420000,2.300000,2.500000,0.07,299.73999,302.89999
462682,WT1,3.0,92.410004,92.410004,92.410004,0.00,8.90,8.000000,9.0,0.48,...,0.000000,0.00,0.000000,0.00,2.420000,2.300000,2.500000,0.07,332.13000,302.89999
462683,WT1,4.0,92.410004,92.410004,92.410004,0.00,7.62,8.000000,9.0,0.43,...,0.000000,0.00,0.000000,0.00,2.400000,2.300000,2.500000,0.07,322.01999,302.89999
462684,WT1,5.0,92.410004,92.410004,92.410004,0.00,7.09,7.000000,8.0,0.46,...,0.000000,0.00,0.000000,0.00,2.410000,2.300000,2.500000,0.07,322.75000,302.89999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
617382,WT1,157676.0,-1.010000,-1.010000,-0.840000,0.01,18.00,17.090000,18.0,0.05,...,16.930000,14.79,17.379999,0.52,35.790001,35.700001,35.900002,0.02,229.27000,231.56000
617383,WT1,157677.0,-1.010000,-1.010000,-1.010000,0.00,17.99,17.469999,18.0,0.05,...,16.969999,15.39,17.389999,0.34,35.810001,35.599998,35.849998,0.06,227.53000,231.56000
617384,WT1,157678.0,-0.810000,-1.010000,1.490000,0.58,18.00,17.770000,18.0,0.01,...,17.040001,15.67,17.420000,0.30,36.060001,35.799999,36.099998,0.10,228.75000,231.56000
617385,WT1,157679.0,-1.000000,-1.010000,-0.620000,0.03,18.00,17.700001,18.0,0.01,...,16.860001,14.86,17.340000,0.60,36.189999,36.099998,36.200001,0.05,226.16000,231.56000
617386,WT1,157680.0,-0.910000,-1.010000,1.080000,0.42,18.00,18.000000,18.0,0.00,...,17.100000,16.17,17.389999,0.15,36.240002,36.200001,36.400002,0.06,226.06000,231.56000